### ISSUE TITLE
Your popup directing us to restore old youtube blocks the option to do so

### ISSUE THREAD

**Issue by MaximilianKohler** [ParticleCore/Particle#606] opened 2017-10-25 04:10 UTC
The bottom right popup with the following text:

> YouTube Plus is not compatible with the YouTube beta Material Layout
Click here for instructions to restore classic YouTube and continue using YT+
When an alpha version is ready for public testing it will be announced here
To keep using the current layout without this message please disable YT+ 

is blocking the option/text/button to restore the old youtube. 

https://github.com/ParticleCore/Particle/wiki/Restore-classic-YouTube

It either needs an 'x' button, or it needs to be moved to the left side. Probably both would be good.

**Comment by ParticleCore** [comment] 2017-10-25 04:16
Duplicate of #550

**Closed by ParticleCore** 2017-10-25 04:16 UTC
Labels: duplicate
