### ISSUE TITLE
Error message covers the Restore Classic Youtube button.

### ISSUE THREAD

**Issue by FiddyFive** [ParticleCore/Particle#581] opened 2017-09-18 03:23 UTC
The "YouTube Plus is not compatible with the YouTube beta Material Layout" covers the Restore Classic Youtube button. This may be resolution specific, in which case I'm using a 1366x768 screen.

![image](https://user-images.githubusercontent.com/32050099/30528250-7c1b79ea-9c74-11e7-8664-ef83cbb45ae1.png)

**Comment by ParticleCore** [comment] 2017-09-18 03:39
Duplicate of https://github.com/ParticleCore/Particle/issues/550

**Closed by ParticleCore** 2017-09-18 03:39 UTC
Labels: duplicate
