### ISSUE TITLE
Disabling autoplay doesn't work for Chrome.

### ISSUE THREAD

**Issue by HighMans** [ParticleCore/Particle#153] opened 2015-11-29 00:37 UTC
Version of Chrome: 46.0.2490.8
Version of Tampermonkey: 3.12
Version of Script: v0.8.2
Operating System: Windows 10 Build 10586.14

I have "Autoplay videos" disabled, however when I open a new youtube video in a new tab and click on the tab, the video plays automatically.

**Comment by ParticleCore** [comment] 2015-11-29 00:58
I have just tested with the same setup, except on Windows 7 instead, the videos do not auto play.

Make sure you have not made any changes to Tampermonkey that might affect YT+

Follow the troubleshooting guide to rule out the possibility of this being caused by something external to YT+ : https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by ParticleCore** [comment] 2015-11-30 18:24
I will close this for now, if you still have problems please follow the instructions above.

**Closed by ParticleCore** 2015-11-30 18:24 UTC
Labels: invalid
