### ISSUE TITLE
Custom Playback Speed

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#234] opened 2016-02-27 13:31 UTC
It would be great if you could add custom playback speed.
Instead of only the default options, let us choose the speed we wish to play the videos.
So instead of having 1.25, 1.5 etc, to have something else. Or add more speed options there.

Here's what I have in mind.
![untitled](https://cloud.githubusercontent.com/assets/7927176/13373106/457f7ed0-dd5e-11e5-9101-5358accf0101.png)
It doesn't necessarily have to be those speeds, it can be other value. I just chose those because it's not much difference from playing it at normal speed, but will end like a minute faster on a 20 minute video with 1.05 speed.

I almost never use the speed options to watch videos. But if there are custom playback speeds I most definitely will.

**Comment by ParticleCore** [comment] 2016-02-27 17:24
Duplicate of https://github.com/ParticleCore/Particle/issues/213

**Closed by ParticleCore** 2016-02-27 17:24 UTC
Labels: duplicate

**Comment by q1k** [comment] 2016-02-27 18:59
I don't think so.
That one is meant to switch automatically to another predefined option, similar to the 'set default quality'.

What I suggested was to replace or add more speed options besides the default ones.

**Comment by ParticleCore** [comment] 2016-02-27 19:11
As far as I could see, to add/change custom speeds would require the entire player to be written from scratch, which means the only viable alternative is to use the existing ones and set a default according to the user preference, this being the linked feature request. Another not so viable alternative is to create a custom controller for this, which I am really not interested in doing. Either way this is a feature I don't find useful for me.

The suggestion made by Eisys in https://github.com/ParticleCore/Particle/issues/213#issuecomment-183896480 gives you the options you want, ranging outside the defaults offered by YouTube. I don't know if it is compatible with YT+ but it looks like it should play well with it.
