### ISSUE TITLE
Disabling the video endscreen

### ISSUE THREAD

**Issue by reddit-is-fun** [ParticleCore/Particle#176] opened 2015-12-29 13:51 UTC
"Endscreen" is a grid layout that pops up after finishing a video. I generally dislike recommendations and I'd like to get rid of this as well. YouTube Center has this setting.
It's nice that you can disable "up next" feature that automatically loads a next video.

![2015-12-29_15-40-50](https://cloud.githubusercontent.com/assets/14923168/12035203/d973f224-ae42-11e5-8315-692d4941ebea.png)

----

I'm sorry if you're unable to accept any feature requests, I did not exactly understand what you mean by this statement. Fortunately this setting should be relatively easy to implement and would make using YouTube more pleasant. Donation is in consideration.

**Comment by ParticleCore** [comment] 2015-12-29 13:54
Duplicate of https://github.com/ParticleCore/Particle/issues/29

**Closed by ParticleCore** 2015-12-29 13:54 UTC
Labels: duplicate

**Comment by reddit-is-fun** [comment] 2015-12-29 13:57
Sorry, I did not find this issue via search.

**Comment by ParticleCore** [comment] 2015-12-29 14:04
There's no problem, that's why I indicate them. In respect to the donation, I do appreciate it and they are very welcomed, but I am not making this extension in exchange of it, it is mostly based on what I find to be useful so that I can keep it light and simple. If I start adding more features beyond this point, even if I had the time and freedom, I would reach a point where maintenance would become a nightmare (YouTube is changing constantly) and I would lose interest on continuing with the project.

**Comment by reddit-is-fun** [comment] 2015-12-29 14:25
@ParticleCore I agree, YTC has too many features and at least currently many of them don't work. I realized that I should be able to block content on YouTube with uBlock Origin, but for some reason it seems to be more trivial with YT than on other sites :/
