### ISSUE TITLE
Embeded videos

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#451] opened 2017-02-04 21:10 UTC
Please enable the options to work on embeds as well.
Not all, but those that can, like disabling annotations, loudness normalization, enabling frame-by-frame mode, and such... essentially those that don't do something with the page, but the video player.
Certainly there is no need to activate the part for changing the youtube logo link on the embedded videos.

**Comment by ParticleCore** [comment] 2017-02-04 21:14
Duplicate of https://github.com/ParticleCore/Particle/issues/38

**Closed by ParticleCore** 2017-02-04 21:14 UTC
Labels: duplicate
