### ISSUE TITLE
Invisible UI

### ISSUE THREAD

**Issue by Corruptinglyneedful** [ParticleCore/Particle#305] opened 2016-08-12 08:42 UTC
UI is invisible no clue what happened.  It just went invisible.

I have reset the settings and cleared cache and cookies.

It is not working.

**Comment by ParticleCore** [comment] 2016-08-12 19:33
Please follow the instructions for reporting a problem: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by Corruptinglyneedful** [comment] 2016-08-13 01:26
Browser Name: Firefox x64

Browser Version: 45.0.1 (because fuck their deprecation and changes to addons)

Operating System: Windows 10 x64

Software Type:  Userscript

Software Version:  1.4.0

Userscript Manager:  Greasemonkey

Userscript Version:  3.8

Problem Description: UI is insible across all of Youtube.  I can still acess it, it's just invisible.

Additional details: Restarted, Rebooted, Cleared Firefox Offline data including Fill forms, cookies, and cache and this is actually when I noticed it went invisible.  P;rior to that happening it was working fine.  I have also hit the reset in the options.

**Comment by ParticleCore** [comment] 2016-08-13 01:36
Did you follow the troubleshooting guide as requested? Otherwise I will have to repeat every step again to ensure this issue is being caused by YT+ and not by something else. Users in the past complained about invisible UI only to later find out they had an add-on (uBlock, uMatrix, etc.) blocking the required image that YT+ needs to show the UI correctly.

**Comment by Corruptinglyneedful** [comment] 2016-08-13 01:45
This is what it looks like: http://i.imgur.com/Won61yu.png

Funny you mention an ad blocker, that was my first thought and it was working with it before and I disabled it just now as a last check and no, it is still invisible.

That part is invisible, the stuff below the player for instance, is not and the options flyup is not, either.

**Comment by ParticleCore** [comment] 2016-08-13 01:49
I asked if you followed the troubleshooting guide for a reason. One of the steps there is to update the YT+ version to the most recent version, which is version 1.4.6. You are still using version 1.4.0, update YT+ to the latest version and see if the problem is resolved, if not then please follow the other steps, otherwise I will have to repeat them again here.

**Comment by Corruptinglyneedful** [comment] 2016-08-13 02:11
I don't want the latest version, but I'll explain why.

You implemented a change I do not like and do not agree with.

This one here is the sole reason I don't want to update:

"The removal of the new endscreen cards has also been reversed since more content creators are relying 100% on them for the endscreen, resulting in awkward empty/strange endscreens when these are absent."

Now that you have taken that option out, the end screen cards will come up again on sponsored videos and enable annotations by deafult on sponsored content, in order to shove ads into my face.  Yes, I can disable annotations manually to get rid of them but I'd have to do that on every single sponsored video.  It doesn't happen on non-sponsors at least in my experience, at least not yet.

Unfortunately, if you don't have some type of solution to solve this big issue and for me this is an extremely big issue, it's the sole reason I left Youtube Center, then I don't know what to do.

I'm going to have to just try reinstalling my same version or something.

Sorry if I sound snippy, I'm just very upset you implemented this change and don't even give an option for those of us whom liked it.

**Comment by ParticleCore** [comment] 2016-08-13 02:38
The newest version has styling changes which are not compatible with the version you are using. The stylesheet, being the same available for any userscript version, has also been updated accordingly and when you cleared your cache your browser downloaded the recent CSS file available, resulting in the problem you reported.

Since you are refusing to update to the newest version then there is nothing else I can do because only updating YT+ is the fix for your problem.

The only alternative you have (and this will have to be done by yourself) is to grab a previous version of the file and include it in your current userscript manually. How you do it will have to be through your own research or you can use Stylish to facilitate this task somehow. Every file I push here has a history tree, and the CSS file has its own as well, so you can fetch the version you like from here (but it is less organized): https://github.com/ParticleCore/Particle/commits/gh-pages/stylesheets/YouTubePlus.css

Just by giving it a quick look I think this is the version that is compatible with 1.4.0 https://github.com/ParticleCore/Particle/blob/66c3e4e37f729cd7c7f7b4c044d255cd0ec3d445/stylesheets/YouTubePlus.css

The problem with deciding to not updating anymore is because YouTube will keep introducing more changes that will eventually cause YT+ 1.4.0 to stop working completely and I have no intention to provide legacy support.

>I'm just very upset you implemented this change and don't even give an option for those of us whom liked it.

The problem here is that users think this is something made for them and because of that they can ask, demand and feel entitled to anything they want, but the fact is that I've made this for myself and, after being persuaded by friends and family, decided to share with everyone that would like to use it as well. It has been this way since the [first day it was released](https://github.com/ParticleCore/Particle/releases/tag/v0.0.1). Any suggestions and improvements are welcome but in the end what matters is what I think, so when it comes to asking for others' opinions I do it but only when it doesn't make me too much difference how that feature should work.

Regarding the end screen cards reversal, the change only affects the [new end screen cards](http://quarterlab.com/youtubes-new-end-screen-feature-2/), not the normal annotations. The normal annotations can still be disabled like before, nothing changed regarding the ability to disable the normal annotations.
You can no longer disable the end screen cards just by disabling annotations, YouTube decided to un-link them from the annotations functionality, which was how they worked before making this task a lot easier.

Since it is clear this issue is caused by using an outdated version I will be closing this.

**Closed by ParticleCore** 2016-08-13 02:38 UTC
Labels: invalid

**Comment by Corruptinglyneedful** [comment] 2016-08-13 02:46
Version 1.4.4 fixed my issue.

Ok, so from that link you provided.  I have literally never seen those.

What I'm actually talking about is Youtube cards, apparently, didn't know the name until you posted that blog.

So we have annotations, Youtube cards, and Endscreen cards.

Annotations and Youtube Cards are what are being used to shove ads in my face, those are what I like disabled.

I have literally not seen an endscreen card on any video eve.  Can you provide me a video of one where you seen it?

**Comment by ParticleCore** [comment] 2016-08-13 02:49
Lots of content creators are starting to use them as the feature becomes more widely available. You can see the new cards at the end of this video, for example: https://youtu.be/fr_6qMM_kU8?t=551

Those areas where the white arrows are pointing at are the new end screen cards. The normal YouTube cards we are used to can still be disabled via annotations, so those are not affected by my reversal.

**Comment by Corruptinglyneedful** [comment] 2016-08-13 02:51
"Those areas where the white arrows are pointing at are the new end screen cards. The normal YouTube cards we are used to can still be disabled via annotations, so those are not affected by my reversal."

Oh, well sorry about that.  It's because I had confused one term with another.

That's great news and won't prevent me from updating in the future.

I really don't like this w/e this is, that Youtube is doing.  Cards and Endscreens, more junk to clutter my viewing experience.

Thank you for helping me.

**Comment by Corruptinglyneedful** [comment] 2016-08-13 02:57
Oh hey @ParticleCore uh just to let you know I viewed that video, the one with endscreen cards, on both versions now.  1.4.4 and 1.4.6 (as I updated) and I didn't notice a difference.

What was exactly happening that caused the reversal of removing end screen cards?

Now, I'm just curious at this point.

**Comment by ParticleCore** [comment] 2016-08-13 03:35
You didn't see any difference probably because you did not disable annotations via the YT+ settings, but via the player settings instead. Had you done so you would see those white arrows pointing at empty space instead of the two cards.

**Comment by Corruptinglyneedful** [comment] 2016-08-13 03:41
You got me there.

Thanks again for helping me and sorry for being an ass.  I mean it was entirely caused by my mistaking terms but yah, I was being an ass.

**Comment by ParticleCore** [comment] 2016-08-13 03:46
Totally comprehensible, there's annotations, normal cards, end screen cards, channel branding and perhaps more new stuff coming we don't even know about. We get used to it eventually.

**Comment by Corruptinglyneedful** [comment] 2016-08-13 03:49
Until someone disables it, kek

Then I'm back to a nice, smooth, uninterrupted viewing experience.  As it damn should be.

**Comment by q1k** [comment] 2016-08-13 12:28
Normal annotations, video recommendations, channel branding, and the info card, can be disabled through the (https://www.youtube.com/account_playback)[YouTube playback settings], as well as through YT+ settings.
Those new cards (that show the video thumbnail, name, and length, and subscribe thumbnail) cannot be disabled anymore in YT playback settings, and YT+ doesn't have that feature anymore.

<br>
But all is not lost, as it was discussed here #298, a simple script could make the cards togglable with the default annotations switch. But for some reason it doesn't work. It works outside YouTube though... it could be because the player hasn't loaded yet, and I don't know how to fix it. Someone more experienced can give it a try, I just can't.


In the meantime I have hidden them with stylish, but as I have many userstyles running it makes it difficult for me to toggle it whenever I want to see what videos are being offered. So the script solution is much better in that regard.

**Comment by Corruptinglyneedful** [comment] 2016-08-13 13:14
In regards to Youtube Playback settings...I've had those suckers disabled for 5 years, didn't stop Youtube Cards from showing up on sponsored content.

It's almost like Youtube LET them bypass my settings to push their ads in my face.

Youtube Center was absolutely useless at blocking this, Youtube Options is the only one I've found that actually does it, so thank you ParticleCore!  Thank you for making an amazing program and sharing with the world so that I can benefit from it.

Thank you for keeping those ad shoving sob's in their place.  I'm so tired of them trying to peddle and shove their damn crap in my face.

I am an avid ad block program user.  I don't let things auto-update.  I read up on change logs before I update.

Do they really think I'm the sort of person that when you shove your ads and marketing bull in my face, is going to make me click it?

HAH!

**Comment by ParticleCore** [comment] 2016-08-13 13:56
>Youtube Options is the only one I've found that actually does it, so thank you ParticleCore! 

Just to clarify, I am not the author of the former YouTube Options, now named SPOI options.

**Comment by Corruptinglyneedful** [comment] 2016-08-13 15:07
Elaborate? Explain?  Wha...What?

It says Youtube Options in the script..

#confused

**Comment by ParticleCore** [comment] 2016-08-13 15:10
>It says Youtube Options in the script..

That is not possible unless you have changed its name which has always been YouTube +:

https://github.com/ParticleCore/Particle/blob/master/src/Userscript/YouTubePlus.user.js#L3

**Comment by q1k** [comment] 2016-09-27 23:34
[I have created a small script](https://github.com/ParticleCore/Particle/issues/298#issuecomment-250029780) that can toggle the cards when the "Annotations" button is clicked.
