### ISSUE TITLE
Please remove 720 60 fps and add 720 30 fps option 

### ISSUE THREAD

**Issue by lukaszpolowczyk** [ParticleCore/Particle#201] opened 2016-01-23 20:02 UTC
Please remove 720 60 fps and add 720 30 fps option in Quuality menu.

**Comment by ParticleCore** [comment] 2016-01-23 20:12
Duplicate of https://github.com/ParticleCore/Particle/issues/177

**Closed by ParticleCore** 2016-01-23 20:12 UTC
Labels: duplicate

**Comment by q1k** [comment] 2016-01-28 14:36
I just want to say that this feature doesn't work on embeded videos (and channel featured video)

**Comment by ParticleCore** [comment] 2016-01-28 19:43
@q1k YT+ is made to not work on embedded videos (see https://github.com/ParticleCore/Particle/issues/38#issuecomment-117966715), only on main YouTube videos and channel trailers. The only option that affects channel trailers is the [autoplay setting](https://github.com/ParticleCore/Particle/wiki/Features#video_autoplay).

The feature is still working correctly for the videos with 60fps streams, which is what it was made for.
