### ISSUE TITLE
Playlist behaviour

### ISSUE THREAD

**Issue by nk-1** [ParticleCore/Particle#384] opened 2016-10-21 07:21 UTC
when:
1. autoplay button is disabled
2. playlist play button is enabled
3. video started from playlist and comes to the end
Then next video from playlist is not started automatically. I suggest to start it if playlist play button is enabled even if autoplay is disabled.

**Comment by nk-1** [comment] 2016-10-21 08:49
Browser Name: Firefox

Browser Version: 45.4.0

Operating System: MacOs 10.11.6

**Comment by Eisys** [comment] 2016-10-21 08:58
Duplicate of #290

**Comment by ParticleCore** [comment] 2016-10-21 09:15
Duplicate of https://github.com/ParticleCore/Particle/issues/290

**Closed by ParticleCore** 2016-10-21 09:15 UTC
Labels: duplicate

**Comment by nk-1** [comment] 2016-10-21 10:19
thank you. Still I don't understand the use case for "Playlist autoplay only controls whether the video should change to the next one in the playlist after the current video ends playback, nothing more." Why would one want to jump to next video without starting it? For me it's very annoying similarly to maingi2 in #290. May you consider to change it to override autoplay or at least make override an option?

**Comment by ParticleCore** [comment] 2016-10-21 10:33
For the same reasons that autoplay up-next control is independent of video autoplay control. Some users (such as myself) want to watch videos in a playlist that was not created by themselves without having to play any unwanted video that they don't like, for example.
The way it currently is implemented you can use the way you want with a single click of a button (or two, if playlist autoplay isn't enabled already), unlike the previous way which would never be possible if it was implemented the way you described since users would no longer be able to stop videos from playing automatically when playlist autoplay was enabled.
The option to override would be redundant when the same behavior can quickly be activated by clicking the video autoplay button available in the advanced options located below the video player.

**Comment by nk-1** [comment] 2016-10-21 15:38
ok, thanks. may be someone else will vote for override later)
