### ISSUE TITLE
[Feature Request] Animate Thumbnails

### ISSUE THREAD

**Issue by cmhrky** [ParticleCore/Particle#414] opened 2016-12-15 14:26 UTC
https://greasyfork.org/tr/scripts/7674-title-youtube-locations

Can be done like this?

Thank you.

**Comment by ParticleCore** [comment] 2016-12-15 19:33
Duplicate of https://github.com/ParticleCore/Particle/issues/40

**Closed by ParticleCore** 2016-12-15 19:33 UTC
Labels: duplicate
