### ISSUE TITLE
Icon to change settings not showing up

### ISSUE THREAD

**Issue by grenzor** [ParticleCore/Particle#76] opened 2015-09-13 09:19 UTC
Browser Name: 

Browser Version: Firefox 40.0.3

Operating System: Linux x64

Software Type: Firefox addon latest version

Problem Description: I just can't fiind the icon on the Youtube page to change settings, seems it's not showing up. I've used this addon in the past on older version and it's worked fine but now I cannot find it.

**Comment by ParticleCore** [comment] 2015-09-13 10:49
Sounds like an issue that I am trying to discover the cause for. Please proceed with the following steps:

Check the DOM and see if the add-on has been inserted correctly into the page. To do this press F12 (or press Ctrl + Shift + K) to open the web console, select the Inspector tab if it isn't already selected and find the element marked by the white arrow in this screenshot example:

![ss](https://cloud.githubusercontent.com/assets/9222661/9836310/5083ad2a-5a04-11e5-8843-d3fa7ebc8b38.png)

If you can find it right click on that script element, select "Copy Outer HTML" and paste it in here so that I can analyze the code.

Also let me know if the element above that one exists (the link element containing the YouTubePlus.css link)

**Comment by grenzor** [comment] 2015-09-13 12:01
I'm guessing you mean on the Youtube page?

I tried that but could not find any scripts that you said.

**Comment by ParticleCore** [comment] 2015-09-13 12:16
Yes, you were correct in assuming that it was on the YouTube page.

So it seems like it is failing to run on the page, so there must be some setting that has been corrupited and is causing the script to fail.

I will need you to find the settings you currently have, to find the file that contains them follow these steps:

In firefox enter the following in the URL bar: `about:support`

Click the `Show Folder` button located in the `Application Basics` table

A folder should show up, locate the `jetpack` folder and open it

Open the folder named `particle@particlecore.github.io`

Open the folder named `simple-storage`

Open the file `store.json`, you should be able to use any basic Linux text application, if it opens correctly you should be able to read the text normally, it cannot show up all garbled. It should look like this:

![ss](https://cloud.githubusercontent.com/assets/9222661/9836661/3c4b7772-5a11-11e5-909e-9a0587e4ef1a.png)


Copy the entire text and paste it here so that I can see if I can find the problematic setting that is causing this problem.

**Comment by grenzor** [comment] 2015-09-13 12:28
{"particleSettings":0}

that is all there is

**Comment by ParticleCore** [comment] 2015-09-13 12:30
Well, that is just not right and I will have to study how such thing was possible. Close Firefox, delete that `store.json` file and then open YouTube, YT+ should be able to load the default settings automatically. I am sorry to say that there was no way of recovering the previous settings you had since the file that should have them was as you just saw.

**Comment by grenzor** [comment] 2015-09-13 12:34
Just deleted the store.json and restarted Firefox and loaded up Youtube but it seems the file does not recreate and the button still does not appear on Youtube.

It's definitely odd but my guess would be it may be a issue with Linux compatibility. In the past, I have come across 1 other addon that works on Windows but the same does not function properly on Linux.

**Comment by ParticleCore** [comment] 2015-09-13 12:37
It shouldn't be relevant which OS you are using. Open the YouTube page with the add-on enabled, press F12 or `Ctrl + Shift + K` to open the web console, enter the following `window.postMessage({set: {}}, "*");`

By the way, which language is being used in YouTube? You can see which one it is at the bottom of any YouTube page.

**Comment by ParticleCore** [comment] 2015-09-13 13:48
From my analysis it seems like this issue is restricted to Firefox only and I suspect it might occur when the browser restarts after updating causing the settings file to be saved with an incorrect value.

Have you managed to restore functionality after following the steps I mentioned?

**Comment by ParticleCore** [comment] 2015-09-14 12:23
I will close this issue for now, if you are still unable to get YT+ working let me know.

**Closed by ParticleCore** 2015-09-14 12:23 UTC
Labels: bug
