### ISSUE TITLE
Highlighting text from description impossible

### ISSUE THREAD

**Issue by Tomaku** [ParticleCore/Particle#173] opened 2015-12-23 22:39 UTC
After you click Show More link in the description it will make text highlighting impossible.

Chrome Canary 49.0.2599.0 x64
YouTube Plus 0.9.2

Works correctly if YouTube Plus is disabled.

**Comment by ParticleCore** [comment] 2015-12-23 23:01
Duplicate of https://github.com/ParticleCore/Particle/issues/150

**Closed by ParticleCore** 2015-12-23 23:01 UTC
Labels: duplicate
