### ISSUE TITLE
Another option to restore old youtube

### ISSUE THREAD

**Issue by dan019** [ParticleCore/Particle#613] opened 2017-11-13 00:59 UTC
Firefox users that delete their cookies when closing the browser do not keep their  "old youtube" settings.

Therefore, I would like to suggest adding this method to the restore classic YouTube page:

Install and use an extension like "[UAControl](https://addons.mozilla.org/en-US/firefox/addon/uacontrol/)" and change the user agent only for youtube.com. Fore example ![aucontroll](https://user-images.githubusercontent.com/18078827/32704884-bfc4cc00-c7da-11e7-9549-9ebf22851c50.PNG)
**Windows**: "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:34.0) Gecko/20100101 Firefox/34.0"
**Linux**: "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:34.0) Gecko/20100101 Firefox/34.0"
**Mac:** "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:34.0) Gecko/20100101 Firefox/34.0"

**Comment by ParticleCore** [comment] 2017-11-13 07:42
Duplicate of #466

**Closed by ParticleCore** 2017-11-13 07:42 UTC
Labels: duplicate
