### ISSUE TITLE
[Feature] - Speed for all videos

### ISSUE THREAD

**Issue by D1mon** [ParticleCore/Particle#416] opened 2016-12-17 18:36 UTC
Please add Option: Default speed (1.0, 1.5, 2.0, 2.5, 3.0) for all videos.

**Comment by ParticleCore** [comment] 2016-12-17 18:38
Duplicate of https://github.com/ParticleCore/Particle/issues/213

**Closed by ParticleCore** 2016-12-17 18:38 UTC
Labels: duplicate

**Comment by D1mon** [comment] 2016-12-17 18:46
Why install a bunch of add-ons when you can Dowa new opportunities in your supplement? This option I need.

**Comment by ParticleCore** [comment] 2016-12-17 18:48
@D1mon please read: https://github.com/ParticleCore/Particle/issues/412#issuecomment-266675363
