### ISSUE TITLE
Frame by frame missing?

### ISSUE THREAD

**Issue by NanoCats** [ParticleCore/Particle#370] opened 2016-10-13 20:47 UTC
Browser Name: Chrome

Browser Version: Chrome 53.

Operating System: Win7 64 bit

Userscript Manager: Tampermonkey

Userscript Version: 1.6.2

Problem Description: The frame by frame target reticule is missing

Steps to reproduce: Unknown

Additional details: The one that enables you to shift and then use the right/left arrowkeys, It only goes by 5s as is the youtube default.

**Comment by ParticleCore** [comment] 2016-10-13 20:50
Duplicate of https://github.com/ParticleCore/Particle/issues/359

**Closed by ParticleCore** 2016-10-13 20:50 UTC
Labels: duplicate
