### ISSUE TITLE
[FEATURE REQUEST] You know how you have the autopause option, can you also add another option for autobuffer too? So we get two options; a no autoplay option and a no autoplay + autobuffer?

### ISSUE THREAD

**Issue by DumbJoe** [ParticleCore/Particle#668] opened 2018-02-12 04:43 UTC
I like to open more than one youtube tab and having them all automatically play before I view them is unacceptable; however some google search led me to your extension for firefox and thought oh cool and tried it out. Yes an autopause option I gasped! Then thought, wouldn't it be better if the video had buffered some before I click play rather than just buffer as I click play? That way the video is then able to play smoothly and responsively when I click play, not *buffer* *buffer* *buffer* *play* *buffer again because my net is so shit* *continue play* *buffer* *buffer* *buffer* *play* *buffer again because my net can't keep up* *continue play* etc., so I can go do something else whilst it loads an buffers by iteself and then come back to it after a while thinking it should be enough time to allow it to buffer half the video or all of it and play.

I think there was another addon I used before this call youtube center that could do just this, unfortunately I think the author must have fucked off leaving his extension broken due the to new changes youtube has done and that newer firefox versions don't accept older extension versions...and thus no longer works... ☹ 

Fast forward a several months, so ever since have been stuck with youtube videos loading all the videos I open at once upon load which gets annoying when you just only wanna watch ONE and not listen to all the audio from the other videos because they're still loading....

**Comment by ParticleCore** [comment] 2018-02-12 09:04
Duplicate of #52

**Closed as completed by ParticleCore** 2018-02-12 09:04 UTC
Labels: duplicate
