### ISSUE TITLE
Youtube Plus not blocking some pre-roll ads even when ticked.

### ISSUE THREAD

**Issue by Corruptinglyneedful** [ParticleCore/Particle#621] opened 2017-11-26 13:54 UTC
Browser Name: Mozilla Firefox

  Browser Version: 56.0 x64

  Operating System: Windows 10 V 1709

  Software Type:  Userscript

  Software Version:  1.9.5

  Userscript Manager:  Tampermonkey

  Userscript Version:  4.5.5590

  Problem Description: Pre-roll Ads keep sneaking in randomly on videos that run ads and typically where ads run, ex. before video, etc I have it set in prefs to block ads within Youtube Plus.

  Steps to reproduce: https://www.youtube.com/watch?v=8PWi_3yeq4c got a pre roll after tab reload on this one and during.  Also this one https://www.youtube.com/watch?v=UhjZsnAYUyE around midway through.

**Comment by ParticleCore** [comment] 2017-11-26 15:14
Cannot reproduce when the option "Disable advertisements in the video page" is activated: https://github.com/ParticleCore/Particle/wiki/Features#video_ads

Make sure you have that option activated. If you do then follow all the troubleshooting steps as requested before opening the issue: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

**Comment by Corruptinglyneedful** [comment] 2017-11-27 03:58
It appears to happen randomly. I just provided videos, I know had pre-roll ads because I got them on it.  I have both options for disabling ads checked in the settings.  "Disable advertisements outside the video page" and  "Disable advertisements in the video page"

**Comment by ParticleCore** [comment] 2017-11-27 08:55
I have been using it for the past week and the only ads that appear are the ones from subscribed channels because I have that option enabled in YT+. If I cannot reproduce the problem I cannot fix it, which is why the troubleshooting is an important step.

**Comment by ParticleCore** [comment] 2017-12-08 15:58
Closing this for now, if you still have any problems follow the instructions in my previous replies.

**Closed by ParticleCore** 2017-12-08 15:58 UTC
Labels: invalid
