### ISSUE TITLE
Complement 'Fit to page in theater mode' with an option to fill to the entire available area

### ISSUE THREAD

**Issue by Hirato** [ParticleCore/Particle#446] opened 2017-01-24 12:24 UTC
I was until just recently, a user of the excellent but abandoned 'YoutubeCenter' extension.

One feature I loved from it was the ability to set videos to 'Fill' the viewport in Cinema Size.
The end result was similar to the 'Fullbrowser mode' option currently provided by this extension, but with 2 key differences; 1) the navbar wasn't covered and 2) I could still scroll up and down.

I'd love if YoutubePlus could provide this same functionality without me needing to fine tune 'Fit to page max width' to get something that's about 95% there.

**Comment by ParticleCore** [comment] 2017-01-24 16:38
Duplicate of https://github.com/ParticleCore/Particle/issues/95

**Closed by ParticleCore** 2017-01-24 16:38 UTC
Labels: duplicate
