### ISSUE TITLE
[Feature] Only play 1 video at a time.

### ISSUE THREAD

**Issue by ldgbc** [ParticleCore/Particle#286] opened 2016-06-29 10:18 UTC
Browser Name: Firefox
Browser Version: 47 stable
Operating System: Windows 10 x64
Software Type: YouTube +
Software Version: v.1.3.3
Userscript Manager: Greasemonkey
Userscript Version: 3.8

Problem Description: Option to, When a video is played, all other video stop.

Steps to reproduce:
1. Open 2 Youtube video
2. Click Play on Video one
3. Change tab to Video 2
4. Click Video 2 to play

Additional details: Both video will play simultaneously (that okay if you want to watch both or more video). Alternatively you will have to "Pause" then change to next video.

Thank you for making this script.

**Comment by ParticleCore** [comment] 2016-06-29 14:34
Duplicate of #52

**Closed by ParticleCore** 2016-06-29 14:34 UTC
Labels: duplicate
