### ISSUE TITLE
YouTube Auto Speed in youtube+

### ISSUE THREAD

**Issue by zihiwoz** [ParticleCore/Particle#577] opened 2017-09-11 15:59 UTC
Hello, can you somehow introduce this script into your extension?
https://greasyfork.org/ru/scripts/25619-youtube-auto-speed
To memorize the speed of video playback.

Ideally, you can make sure that the channels on which the playback speed x1.1 - x1.5

bookmarklet:
javascript:(function(){document.getElementsByClassName(%22video-stream%20html5-main-video%22)[0].playbackRate=0.25})();

**Comment by ParticleCore** [comment] 2017-09-11 16:36
Duplicate of https://github.com/ParticleCore/Particle/issues/454

**Closed by ParticleCore** 2017-09-11 16:36 UTC
Labels: duplicate
