### ISSUE TITLE
Comment tree auto expanding

### ISSUE THREAD

**Issue by Hotohori** [ParticleCore/Particle#468] opened 2017-03-07 14:53 UTC
Browser Name: Firefox

Browser Version: 50.1.0

Operating System: Windows 8.1

Software Type: Addon

Software Version: 1.7.8

Problem Description: The new feature to jump to a new comment expand all Posts with more answers when you scroll to them

Steps to reproduce: Click on a notice for a new answer to jump to the new answer and scroll to other comment trees and stop over them

------

Old post:

It seems a new "feature" since one of the last updates is in the addon, that when I scroll down in the comment section a commentary with many answers are automatically expanding.

It may be useful for some users, but I often hate it. Some minutes ago I want to edit a comment from myself and before I could hit the "edit" Button the tree above my comment was expanded.

**I really want an option to deactivate this behavior.** I searched already 2 weeks ago and can't find something and again and again I run into that feature and the most time I don't want that.

It annoys me so much, that beside all that great feature I thought about to deactivate the complete addon, deinstalling it or searching for an alternative. I only write that to make it clear how much it annoys me, I really don't want to go so far and hope you can build in an option to deactivate this. :)

**Comment by ParticleCore** [comment] 2017-03-07 20:02
YT+ does not have any auto expanding feature for comments, whatever is causing this it is caused by something else. Follow the troubleshooting guide like it was requested before opening the issue: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by Hotohori** [comment] 2017-03-07 22:24
It have that is some way, I found the Issue. It only happens when I open a YT Video with new comments where I was commenting before, than all Posts with more answers will expanding when I scroll to them.

So far I have seen this was one thing in the last update and the date matches pretty good to the point since I have this "feature". So no new feature, it is a bug.

**Comment by ParticleCore** [comment] 2017-03-08 01:48
Ohhh, I was finally able to replicate it! Nasty one, the strangest thing is that I did test if there were any problems before releasing https://github.com/ParticleCore/Particle/issues/450 and at that time nothing like this happened. Will try to push a fix for this as soon as possible, thanks for the detailed instructions.

**Closed** 2017-03-08 03:47 UTC
Labels: bug

**Comment by ParticleCore** [comment] 2017-03-08 03:53
@Hotohori  I have released version 1.8.0 with a fix for this issue, let me know if it works correctly for you as well. If you are using the Addon version hosted on AMO you should know that the review queues have been taking a massive amount of time and you should not receive it any time soon. This is something outside my control, but an alternative is to use the addon hosted on Github if you don't want to wait.

**Comment by Hotohori** [comment] 2017-03-08 04:08
Have used Github. Seems to work fine so far, have tested it with some oft my notices. Thanks for the fix, that was really fast. Awesome Addon. :)
