### ISSUE TITLE
Improve 'Fit to page' Feature By Setting Height

### ISSUE THREAD

**Issue by JamesCoyle** [ParticleCore/Particle#421] opened 2016-12-27 14:01 UTC
While having the max width option to ensure the video doesn't appear offscreen works for most situations, it fails if the user often switches between different aspect ratios. It would be better to set the width of the video to be the width of the viewport as it is currently but also set the height of the video to be the height of the viewport minus the height of the top bar. This would make the video and the top bar fill the entire screen when a video is loaded and allow the user to scroll down to see the description and comments.

**Comment by q1k** [comment] 2016-12-27 14:13
Height us still not set?
It should be 100vh

**Comment by JamesCoyle** [comment] 2016-12-27 15:30
I'm talking specifically about the feature which expands the video when in theater mode not fullbrowser mode.

**Comment by q1k** [comment] 2016-12-27 20:51
As a temporary fix, you can add this to stylish.

```
.part_fit_theater .watch-stage-mode #player-api,
.part_fit_theater .watch-stage-mode #player-unavailable {
  max-height: calc(100vh - 85px) !important;
}
```
Adjust the `px` as necessary.

**Comment by ParticleCore** [comment] 2016-12-27 20:54
Duplicate of https://github.com/ParticleCore/Particle/issues/77

**Closed by ParticleCore** 2016-12-27 20:54 UTC
Labels: duplicate
