### ISSUE TITLE
Feature Request: Easy way to exit cinema mode

### ISSUE THREAD

**Issue by jishnu7** [ParticleCore/Particle#340] opened 2016-09-21 06:44 UTC
Exiting cinema mode by anywhere outside the video, might be easier than the current method to exit. 

There are other plugins which have this way of interaction.

**Comment by ParticleCore** [comment] 2016-09-21 09:06
Duplicate of https://github.com/ParticleCore/Particle/issues/205

**Closed by ParticleCore** 2016-09-21 09:06 UTC
Labels: duplicate

**Comment by jishnu7** [comment] 2016-09-21 09:10
Original issue is also closed, right? any particular reason?

**Comment by ParticleCore** [comment] 2016-09-21 09:14
Exiting by clicking outside the video will prevent any interaction during cinema mode (commenting, like/dislike videos, add to playlists, etc.) and exiting by shortcut key will cause conflicts with YouTube player shortcuts. For now it will stay as it is, but I will not discard the possibility of finding an easier method for exiting cinema mode.

**Comment by jishnu7** [comment] 2016-09-21 09:15
Can it be at least an opt-in feature?

**Comment by ParticleCore** [comment] 2016-09-21 09:18
I already explained it will stay as it is for now:

>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md

**Comment by jishnu7** [comment] 2016-09-21 09:19
I can try sending a PR if you are ok with the method?

**Comment by ParticleCore** [comment] 2016-09-21 09:25
I am sorry but I cannot accept that, please don't insist anymore. If you wish to create your own fork it is fine by me, or PR a locale as well, but not code changes.

**Comment by q1k** [comment] 2016-09-21 14:17
How about light off only when video is playing...

```
#movie_player.playing-mode {
    z-index: 2147483647 !important;
  }
  #player .player-api {
    z-index: auto !important;
  }
  #movie_player:before {
    content: "";
    position: fixed;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
    background: rgba(0, 0, 0, 0.8);
    opacity: 0;
    transition: opacity 0.5s ease-in-out;
    pointer-events: none;
    
  }
  #movie_player.playing-mode:before {
    opacity: 1;
    
  }
```

Create a new style in stylish, and add the code above

**Comment by ParticleCore** [comment] 2016-09-21 21:25
@q1k Cinema mode alreday turns only only when the video is playing, he wants a different way of exiting it, not entering.

**Comment by q1k** [comment] 2016-09-22 00:24
> @q1k Cinema mode already turns on only when the video is playing, he wants a different way of exiting it, not entering.

It also stays ON when video is paused.
With the above code cinema mode will be off when video is paused.

**Comment by ParticleCore** [comment] 2016-09-22 17:58
Ah, understood, so it just stays dark only when the video is playing and in no other state.
