### ISSUE TITLE
Freezing tabs in Chrome v51 while video is playing

### ISSUE THREAD

**Issue by DAOWAce** [ParticleCore/Particle#425] opened 2017-01-07 03:08 UTC
Copypaste edit of my review:

Within the last 2 weeks (of Dec 16) I've noticed my Youtube tabs completely hanging. The video still plays with its audio, but the entire tab is hung up and can't be interacted with. It also turns the mouse cursor invisible while over the page. It takes a while to close or reload the tab as well.

I'm using Chrome v51.  I cannot use a later version of Chromium because DirectWrite was forced on in v52 and makes text unreadable for me, actually causing me eye strain because of the way it's rendered.  Many other people share this opinion and it's probably been one of the biggest outcries of Chrome in the last few years.  There is no possible method to get the old GDI rendering back; it is completely removed from the browser's code.

After an extensive period of time and toggling the addon on/off, I've noticed that the issue does not appear with the addon disabled. I still don't have a reliable way to reproduce this as it seems entirely random, but any time the issue showed up, the addon was enabled. I've never experienced the issue with the addon disabled.

Maybe it works as designed in updated Chrome versions, but updating is completely out of the question; I would rather go back to PaleMoon.

Chrome 51.0.2704.106  64bit
Current YT+ version is 1.7.5.  At the time I originally wrote my review I believe it was version 1.7.3 _(which looks like it made a change to the floating player code.. possible regression? I don't use the floating player)_
Windows 7 x64.

**Comment by ParticleCore** [comment] 2017-01-07 04:42
I'm afraid there isn't much I can do, it is not like I can download an older version and run it along the newest I already have installed to find out if I can replicate this problem and what is causing it in order to fix it.

Just because the issue goes away when YT+ is disabled does not mean that it is being caused by it, there could be another extension or even a browser setting that causes the conflict when YT+ is enabled.

Aside from asking you to follow the troubleshooting guide here: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

I can only suggest you to also try testing it with the floating player disabled (https://github.com/ParticleCore/Particle/wiki/Features#floating_player), since you mentioned at the end.

**Comment by DAOWAce** [comment] 2017-01-07 07:10
I stated I **didn't** use the floating player, I was just assuming that there _may_ be a regression in 1.7.3 as code that had to do with the player was changed (again, assuming).  This issue only started appearing around that time.  My addons have not changed at all, other than being automatically updated periodically (Stylish, uBlock Origin, Reddit Enhancement Suite, Enhanced Steam)

I've tried to google about it, but there's nothing relevant that comes up.  This leads me to believe it's an issue with either this addon or using an older Chrome version, or both.

I don't have Firefox installed (technically). I use Pale Moon, but because it didn't fully support the HTML5 player, I switched to Chrome for Youtube (~2 years ago).  It's a poor experience otherwise, as there is microstutter _(something's wrong with my PM profile; negatively affects all media)_ and the lack of 60FPS video was terrible.  The recently released v27 of PM added MSE support so Youtube can play HTML5 60FPS videos.. but only up to 1080p, and a few of the content creators I watch upload above 1080p video and the quality reduction is pretty severe for some of them, mainly gaming. _(v27 also has numerous other problems that affect me; waiting for updates before I switch)_

Maybe giving you my config would help?

```
{
  "BLK_ON": true,
  "GEN_BLUE_GLOW": true,
  "GEN_BTTR_NTF": true,
  "GEN_CHN_DFLT_PAGE": "videos",
  "GEN_CMPT_TTLS": true,
  "GEN_DSBL_ADS": false,
  "GEN_DSB_HVRC": false,
  "GEN_GRID_SRCH": false,
  "GEN_GRID_SUBS": false,
  "GEN_HDE_CHN_SDBR": false,
  "GEN_HDE_RECM_SDBR": false,
  "GEN_HDE_SRCH_SDBR": false,
  "GEN_HIDE_FTR": false,
  "GEN_INF_SCRL": true,
  "GEN_LOCL_LANG": false,
  "GEN_PPOT_ON": true,
  "GEN_REM_APUN": false,
  "GEN_SDBR_ON": true,
  "GEN_SPF_OFF": false,
  "GEN_SUB_LIST": true,
  "GEN_YT_LOGO_LINK": true,
  "VID_CTRL_BAR_CLR": "dark",
  "VID_DESC_SHRT": true,
  "VID_DFLT_QLTY": "hd1440",
  "VID_END_SHRE": true,
  "VID_HIDE_COMS": "0",
  "VID_HIDE_DETLS": false,
  "VID_LAYT_AUTO_PNL": true,
  "VID_PLR_ADS": false,
  "VID_PLR_ALACT": false,
  "VID_PLR_ALVIS": false,
  "VID_PLR_ALVIS_WDTH": false,
  "VID_PLR_ANTS": false,
  "VID_PLR_ATPL": false,
  "VID_PLR_CC": false,
  "VID_PLR_CTRL_VIS": false,
  "VID_PLR_DASH": false,
  "VID_PLR_DYN_SIZE": true,
  "VID_PLR_FIT": true,
  "VID_PLR_FIT_WDTH": "1280px",
  "VID_PLR_HFR": false,
  "VID_PLR_HTML5": true,
  "VID_PLR_INFO": false,
  "VID_PLR_SIZE_MEM": true,
  "VID_PLR_VOL_LDN": true,
  "VID_PLR_VOL_MEM": false,
  "VID_PLST_ATPL": true,
  "VID_PLST_RVRS": true,
  "VID_PLST_SEP": true,
  "VID_POST_TIME": true,
  "VID_PPOT_SZ": false,
  "VID_PROG_BAR_CLR": "red",
  "VID_SDBR_ALGN": "1",
  "VID_SUB_ADS": false,
  "VID_TTL_CMPT": false,
  "VID_VID_CNT": true,
  "VID_VOL_WHEEL": false,
  "advOpts": true,
  "blacklist": {},
  "extLang": {},
  "firstTime": false,
  "floaterX": 0,
  "floaterY": 0,
  "plApl": true,
  "plRev": false,
  "theaterMode": true,
  "volLev": 50
}
```

**Comment by ParticleCore** [comment] 2017-01-07 11:52
I have tested with your settings for a few hours and no lag/stutter/hanging took place, however I have an updated Chrome version so that might be a factor as well.

The fact that your extensions haven't changed is not relevant, they do update and they might introduce new code/behavior that could be conflicting with YT+ at some point, which is why following the troubleshooting guide is not a suggestion, it is something that has to be done because the steps listed there are the same steps I would have to ask here again.

I already understood that you do not wish to update Chrome, but all the other steps have to be followed: try with everything disabled except YT+, try with a new clean and temporary Chrome profile with just YT+ installed, etc. If you refuse to follow those steps, which I would have asked here just as well, and I already explained that I cannot replicate your problem, then there is next to nothing I can do on my end.

The last thing I can think of for you to try, besides actually following the troubleshooting guide, is for you to see if the same problem is present with the userscript version. Just install Tampermonkey and then load the userscript from here: https://github.com/ParticleCore/Particle/raw/master/src/Userscript/YouTubePlus.user.js

Remember to disable the extension version, otherwise you will have 2 YT+ trying to run at the same time.

At this point I have no idea what else can be done and if you still refuse to follow the troubleshooting guide and refuse to update Chrome then I am left with nothing other than raising the minimum Chrome version to prevent other users from going through the same problem.

**Comment by ParticleCore** [comment] 2017-01-07 12:23
I was finally able to find an older Chrome version (the same as yours) and I am currently testing it under a clean Windows profile so it won't switch to the newest Chrome version. So far I haven't been able to detect the problem you mentioned, but I will continue testing it for a few more hours. Without any sure way to reproduce the lag I can't say I will ever be able to see if the problem is related to YT+ or not, so it is very important that you follow the troubleshooting guide.

A list of your extensions could also be helpful to see if any of them is clashing with YT+.

**Comment by ParticleCore** [comment] 2017-01-08 22:19
After quite some time trying to replicate this problem I am afraid that I have not been able to replicate it using the same Chrome version as yours, same YT+ settings and OS configuration. Whatever is causing your problem is either related to your Chrome settings, extension or something else you might have installed which is only noticeable when YT+ is being affected, which is why it is important that the troubleshooting guide is followed exactly as it is laid it and not just what users think might or might not be worth trying.

**Comment by ParticleCore** [comment] 2017-01-10 22:25
I will close this for now, if you are still having problems follow the instructions previously provided.

**Closed by ParticleCore** 2017-01-10 22:25 UTC
Labels: invalid

**Comment by DAOWAce** [comment] 2017-01-13 13:21
I'll try to get around to testing with -all- addons disabled and potentially a new profile, but that's quite a difficult thing to commit to as using the internet without addons is a poor experience.. and in the case of ads, potentially dangerous (sole reason I use adblocking addons is due to being hit with drive by malware in the past which compromised my accounts).

Just wanted to update though that I still experienced the same issue with the userscript version (and 1.7.6 release).  I did not copy my settings over.

I'm going to test my theory of a regression and try using an older version with the userscript.  If I still experience the issue, this will help me root out what's really causing it.

**Comment by DAOWAce** [comment] 2017-01-26 11:15
Reverting back didn't do anything; bug still exists.

I am leaning strongly to this being an issue with a change Youtube made that affects the older chrome version.  I still do not have any way of reliably reproducing the issue; it is seriously random as to when it happens.  Sometimes I can go a few days without seeing it, other times it happens over and over on a single video for a set period of time then just be fine later.  I don't get it.

**Comment by ParticleCore** [comment] 2017-01-26 13:19
Then please try with the most recent Chrome version, if the issue goes away then we know this was a problem with that browser version which was eventually fixed at a certain browser version. Whatever the cause might be, it is something YT+ cannot by any means resolve since I couldn't replicate it even when using the same version as yours.
