### ISSUE TITLE
Feature requests.

### ISSUE THREAD

**Issue by BiZZKeryear** [ParticleCore/Particle#426] opened 2017-01-07 21:14 UTC
I came here from the abandoned Youtube Center (https://github.com/YePpHa/YouTubeCenter) and there are a few features I'd like to have.
1. Download. It can come in handy if you are making a video reply to someone to have a fast and easy way to download the video (though I could fire up JDownloader)
2. Scrolling up a few times at the top of the page to go in full browser mode (and scrolling down to exit it)
3. Resizing video window to a percentage of browser window (I personally like 90% best, cause I still can see the whole page while having the video the dominant part)
4. Automatically expand (or hide entirely) the description. I read them all the time first ... but some will never, and actually prefer if it would exists at all.
5. Able to decide what size the size buttons of the video will make it.

Thanks in advantage (and if you not sure what I mean with some of my points, either ask or check out the ... now almost completely broken ... YTCenter and maybe recycle some code of it)

**Comment by ParticleCore** [comment] 2017-01-07 21:18
1. Duplicate of https://github.com/ParticleCore/Particle/issues/32

3. https://github.com/ParticleCore/Particle/wiki/Features#fit_max_width

4. https://github.com/ParticleCore/Particle/wiki/Features#hide-video-details and https://github.com/ParticleCore/Particle/wiki/Features#auto-expand-video-description

As for the rest: 

>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md

**Closed by ParticleCore** 2017-01-07 21:18 UTC
Labels: feature
