### ISSUE TITLE
[Suggestion] Autoplay in play-lists, but not elsewhere

### ISSUE THREAD

**Issue by kangarko** [ParticleCore/Particle#214] opened 2016-02-15 11:10 UTC
It would be great if one could choose to start playing videos automatically in playlist, but not elsewhere. Now it is only possible to disable/enable autoplay globally, which is frustrating in playlists.
Thank you.

**Comment by ParticleCore** [comment] 2016-02-15 12:07
Duplicate of #30.

**Closed by ParticleCore** 2016-02-15 12:07 UTC
Labels: duplicate
