### ISSUE TITLE
"Open in pop-out" missing

### ISSUE THREAD

**Issue by NotLazy** [ParticleCore/Particle#309] opened 2016-08-15 11:07 UTC
Browser Name: Firefox

Browser Version:  47.0

Operating System: Windows 10

Software Type: Userscript

Software Version: 1.4.7

Userscript Manager: Greasemonkey

Userscript Version: 3.8

Problem Description: The "open in pop-out" button doesn't appear on a channel's video list page

Steps to reproduce: just go to any channel, go to "videos" and the hover button "open in pop-out" is missing

Additional details: Even though the troubleshooting says firefox 48, i checked for updates and firefox is up to date, but everything else works. the "open in pop-out" works on a video page, and player modifications work.

**Comment by ParticleCore** [comment] 2016-08-15 11:09
Duplicate of https://github.com/ParticleCore/Particle/issues/307

**Closed by ParticleCore** 2016-08-15 11:09 UTC
Labels: duplicate
