### ISSUE TITLE
Youtube vol mouse over fail using chrome latest

### ISSUE THREAD

**Issue by SuitYourself** [ParticleCore/Particle#433] opened 2017-01-11 08:47 UTC
Problem Description: controlling the volume over mouse gesture enabled by me in the YT plus. Not working.

Additional details: sound just go to 10% and stops going up and i can't control the volume. But i can with by clicking with the mouse.

This was posted by another user the thread was closed assuming it was not an issue.

Well it is an issue.

Using latest chrome and yt+

**Comment by ParticleCore** [comment] 2017-01-11 09:17
No problem, since I was able to confirm the problem on my end I re-opened the other issue so we we can reuse it.

I will mark this as duplicate of the other to keep things organized: https://github.com/ParticleCore/Particle/issues/432

**Closed by ParticleCore** 2017-01-11 09:17 UTC
Labels: duplicate
