### ISSUE TITLE
Feature request (because I couldn't find where to submit one)

### ISSUE THREAD

**Issue by TheEssemCraft** [ParticleCore/Particle#343] opened 2016-09-28 23:52 UTC
Hey,
I have a feature request. My request is to add the ability to check the video quality/FPS of a video, because it is very useful when checking if a video looks good or not. That's just one way it could be used; for example, on the bait-and-switch channel SiIvaGunner, even though most of the videos are static, it would be useful to see an unexpected twist coming (marked by the FPS). The YouTube Center userscript has this feature, and I'm currently looking for an alternative that has this feature. Thanks in advance.

P.S. Can you also add the country flags from said userscript?

**Comment by q1k** [comment] 2016-09-29 03:17
This has been discussed before, #80 .
As much as I would like to see the thumbnail options, I don't think it will be added to this script anytime soon.

As for the country flags, those will probably never come back. Because the api used for them is no longer available, it hasn't been for a good few years now.

**Comment by ParticleCore** [comment] 2016-09-29 08:28
Duplicate of https://github.com/ParticleCore/Particle/issues/80

As for the country flags q1k already covered it, the API no longer provides this information and it can't be obtained from anywhere else for quite some time now.

**Closed by ParticleCore** 2016-09-29 08:28 UTC
Labels: duplicate

**Comment by TheEssemCraft** [comment] 2016-09-29 21:02
But wait. YouTube Center does it in 2016...

**Comment by ParticleCore** [comment] 2016-09-29 21:20
I assure you it does not, I just tested it to confirm it.
Neither YouTube Center, Magic Actions, YouTube Options or any similar YouTube extensions are capable of showing country flags anymore because YouTube no longer provides that information since the YT API V2 has been deprecated.

**Comment by TheEssemCraft** [comment] 2016-09-30 02:57
Here's a screenshot taken a few hours before the time this comment was posted: http://i.imgur.com/eO7ZBel.png?1

**Comment by ParticleCore** [comment] 2016-09-30 08:15
It polls the data from the only channels that have made their country known, see "Country: Netherlands"

https://www.youtube.com/channel/UC9ecwl3FTG66jIKA9JRDtmg/about

Everyone else that hasn't done the same thing will never be able to show its country flag.

Example channels where no country flag is shown because of the problem above:

https://www.youtube.com/watch?v=7Fahnl7Scxw

https://www.youtube.com/watch?v=OP_DyNu4QJI

However, this is something that wasn't possible before, they have probably changed it some time this year because even the YTC author found that there was no way of finding the countries since the API changes, perhaps now we can but only if the channels themselves have made that information public in their About page.

Either way, as it was already said before in similar requests, I am not interested in adding such feature for the moment.
