### ISSUE TITLE
"Restore old youtube" option missing

### ISSUE THREAD

**Issue by DeluxeTux** [ParticleCore/Particle#677] opened 2018-03-12 23:46 UTC
Clicking on the icon in the top right no longer shows the restore old youtube button. I can't find the option to disable material youtube anywhere. I'm using firefox.
Thanks

**Comment by ParticleCore** [comment] 2018-03-13 01:52
Duplicate of #674

**Closed as completed by ParticleCore** 2018-03-13 01:52 UTC
Labels: duplicate

**Comment by WindowsWorkaround101** [comment] 2018-03-19 23:14
https://greasyfork.org/en/scripts/32906-get-me-old-youtube this fixed the issue for me instantly. It just sets a cookie to automatically make it load into the Old YouTube. Whether you can collaborate with the creator of this, make your own version, or just inform others to use it, this would fix it.
