### ISSUE TITLE
Full Screen Mode - Auto Play Failure

### ISSUE THREAD

**Issue by SuitYourself** [ParticleCore/Particle#449] opened 2017-02-03 10:56 UTC
G'day Mate. Using latest chrome, windows 7, 1.77 addon.

When youtube is in full screen mode, auto play won't load up next video. Says it will, does the rotating wheel, then comes up with static screen and says error.

When 1.77 addon is turned off, auto play works fine in full screen mode.

Hopefully you can reproduce.

Cheers mate.

**Comment by ParticleCore** [comment] 2017-02-03 13:05
Cannot replicate, the autoplay up next loads the next video without any problems. Please follow the troubleshooting guide to see if there is something on your end causing your problem: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

**Comment by ParticleCore** [comment] 2017-02-05 00:05
I will close this for now, if you are still having trouble follow the instructions in the previous reply.

**Closed by ParticleCore** 2017-02-05 00:05 UTC
Labels: invalid

**Comment by SuitYourself** [comment] 2017-02-05 16:15
No worries man. Tonight it started working perfectly fine for me. I can't explain it. :)

**Comment by SuitYourself** [comment] 2017-02-06 08:51
Started happening again to me. I did turn on the error catcher, not sure if that is helpful or anything to do with this issue.

![image5](https://cloud.githubusercontent.com/assets/25052021/22640182/40632bf0-ec9d-11e6-977d-1138ee6b0f36.jpg)

**Comment by ParticleCore** [comment] 2017-02-06 09:26
This error occurs when users install recent Chrome extensions on old Chrome versions: http://stackoverflow.com/questions/23918539/extension-installed-from-chrome-webstore-throws-error-package-is-invalid-detai

or if the user is not installing the extension directly from the Chrome webstore: http://stackoverflow.com/questions/29456462/cannot-load-extension-with-file-or-directory-name-metadata

This issue is also usually related to using old Chrome versions (<31).

It has nothing to do with YT+, that folder is added automatically by the Chrome webstore.
I already asked for you to follow the troubleshooting guide in my first reply and before you opened the issue, you decided not to, therefor there is nothing else I can do here.

**Comment by SuitYourself** [comment] 2017-02-06 10:58
You assume I didn't listen or follow your instructions? 

I was only trying to help by posting that picture.

Here's another:

![image1](https://cloud.githubusercontent.com/assets/25052021/22644619/05e2442c-ecaf-11e6-9b5f-4a13a5e89b95.jpg)

**Comment by SuitYourself** [comment] 2017-02-06 10:59
Thanks for your prompt reply though. I'll leave you be.

**Comment by ParticleCore** [comment] 2017-02-06 11:07
I assume it correctly because in the last step in that guide it asks to post using the provided template with all the information that is requested, which is something you haven't done once. That guide contains the most common steps I ask to users when trying to troubleshoot the problem, when a user does not want to follow it then providing further support becomes a pointless task.

Whichever the cause of your problem is, it is something that only you are having and the causes can be plenty: Outdated Chrome version, despite saying you have the "latest" this means nothing to me, you might think you have the latest when in fact your browser could have problems updating for a while, which is why the version number is relevant and "latest" means nothing. It could also be a browser setting that is affecting normal behavior of the extension, which is why one of the guide steps is to try with a fresh profile, etc.

**Comment by SuitYourself** [comment] 2017-02-06 11:09
I'm trying to figure out what is going on. Probably some secondary installation of the thing somewhere. :)
