### ISSUE TITLE
Grid-mode search results conflicts with YT's new layout

### ISSUE THREAD

**Issue by LeLobster** [ParticleCore/Particle#400] opened 2016-11-10 18:01 UTC
You're probably already aware of this but thought I'd create an issue for it anyway so it's documented.  
Youtube's new beta(?) layout has increased size of the thumbnails in the search results and having grid mode enabled in YT+ causes it to overlap on each other.
Getting the new layout is random for me and most of the time I still get the normal layout, but it does happen on occasion.

**Comment by ParticleCore** [comment] 2016-11-10 22:23
Duplicate of https://github.com/ParticleCore/Particle/issues/400

Yes, YT+ isn't compatible with the Material layout but once it stabilizes I will try to work on it.

**Closed by ParticleCore** 2016-11-10 22:23 UTC
Labels: duplicate
