### ISSUE TITLE
Issue #314 returned?

### ISSUE THREAD

**Issue by SingularityRS** [ParticleCore/Particle#323] opened 2016-09-01 01:38 UTC
I've noticed that sometimes the lag described on issue #314 returns. And it seems to be even more severe when it does happen. When trying to scroll, the page "hangs" and is generally very sluggish. Interacting with the page is sluggish as well (by interaction, I mean hovering my cursor over something on the page). And videos also take longer to actually start.

The "fix" appears to be a page refresh (rarely it requires a disable and re-enable). And with Tampermonkey, it seems to require a disable and re-enable (of both the script and sometimes even the Tampermonkey extension itself - I don't use this enough to fully observe its behaviour compared to the normal YT+ chrome extension though).

I don't really know how to re-produce this problem. It seems random. I do (most of the time) always notice it when I first load up Chrome for the day - it almost always happens.

From what it looks like, the fix implemented for #314 is sometimes not triggering. At least that's what I think it is. 

The pages I frequent are the same as shown in the screenshot on #314 (basically page that contains playlist bar)

Since I also re-installed the extensions for another small issue I had (that I reported and almost immediately remedied the issue), I know simply uninstalling and reinstalling wouldn't help.

**Comment by ParticleCore** [comment] 2016-09-01 01:48
Have you tested this with everything disabled except YT+? Reset its settings to default? Try the extension version to see if the same problem is present in that version? Try seeing if the problem is present with YT+ disabled?

The fix is not toggle-able, it is always in effect. I cannot detect any spikes while scrolling the same pages I tested before, or other pages so I am mostly certain that it isn't the same issue.

Also has it always been like this since the fixed version was released or is it something that recently started happening?

**Comment by SingularityRS** [comment] 2016-09-01 21:00
The problem with testing this bug is its randomness. It can be fine one minute and then all of a sudden, the lag comes and its pretty damn severe. I have to either disable the extension and re-enable, or do a page refresh for the lag to disappear.  I cannot predict, or re-produce this bug myself. It either comes or it doesn't. That's the worst thing about it. Sometimes, it can not appear for hours and then it comes back like, "Forgot about me? I'm back to slow you down!". Idk.

Settings are at default. This lag can occur on any page within YouTube. It's highly noticeable when it does happen. If I were to test each and every scenario, it would probably take a long time because of its randomness and I could think it's fixed, when it really hasn't (because of its tendency to hide and not cause problems). 

I've looked at Task Manager during this lag outburst and can't see anything wrong there (compared to it being disabled).

I don't remember what it started happening. There's times where I haven't used YouTube much. It did happen on version 1.4.9 though.

Like I said, when it's working fine, it's smooth as hell with no lag visible at all. However, when the bug activates, it becomes sluggish (and it's quite severe too) and requires a page reload, or a disable/re-enable of the extension to temporarily kill it.

**Comment by ParticleCore** [comment] 2016-09-01 21:11
The problem with this is that I cannot find any cause just with this little information, which is why I asked you to test the way I said. Even if it is random it is apparently recurring, which means that you can see if it happens again with YT+ disabled, or everything disabled except YT+. The only difference is that you have to test it for a longer time unlike before. If during one of the tests it goes with no lag for a noticeable long period (longer than what it took for lag to occur) then we already reduced the possible causes.

This could be caused by another extension you have that might have updated recently, or something else completely different, which is why the testing is absolutely necessary, especially because I cannot replicate it.

A last resort would be to disable SPF in YT+, but ideally fixing the problem would be the best option.

**Comment by ParticleCore** [comment] 2016-09-02 16:04
I will close this for now. If you are still having trouble please follow the previous instructions, and you don't have to open a new issue, you can continue posting here and I will see it.

**Closed by ParticleCore** 2016-09-02 16:04 UTC
Labels: invalid
