### ISSUE TITLE
[Request] Remember/Set play speed

### ISSUE THREAD

**Issue by BaconCatBug** [ParticleCore/Particle#320] opened 2016-08-27 11:41 UTC
I would like to see an option to remember the speed or set the default speed of what videos are played at, as I watch all content at 1.5x speed. :)

**Comment by ParticleCore** [comment] 2016-08-27 11:44
Duplicate of https://github.com/ParticleCore/Particle/issues/213

**Closed by ParticleCore** 2016-08-27 11:44 UTC
Labels: duplicate
