### ISSUE TITLE
Feature Request: Non-DASH formats and video pre-buffering

### ISSUE THREAD

**Issue by Ofunniku** [ParticleCore/Particle#427] opened 2017-01-07 23:17 UTC
a page from YTC's book; a "disable autoplay" that still allows the videos to buffer fully (non-DASH formats)

**Comment by ParticleCore** [comment] 2017-01-07 23:19
Duplicate of https://github.com/ParticleCore/Particle/issues/328

**Closed by ParticleCore** 2017-01-07 23:19 UTC
Labels: duplicate
