### ISSUE TITLE
Option to disable share panel after liking any video on YouTube, maybe?

### ISSUE THREAD

**Issue by Piter432** [ParticleCore/Particle#237] opened 2016-03-11 16:47 UTC
I mean about almost the same option as disabling the share panel after video ended, but in this one, after liking any video on YouTube, because I don't like that share panel shows me after I like any video :/

**Comment by ParticleCore** [comment] 2016-03-11 16:57
Duplicate of https://github.com/ParticleCore/Particle/issues/43

**Closed by ParticleCore** 2016-03-11 16:57 UTC
Labels: duplicate

**Comment by Piter432** [comment] 2016-03-11 16:59
Ah, okay. Forgot to use search, he, he :P
