### ISSUE TITLE
subscriptions page cut off on top

### ISSUE THREAD

**Issue by Daisenki** [ParticleCore/Particle#526] opened 2017-07-11 12:53 UTC
I have this issue now since a few weeks but didn't make a issue here, but now it gets really annoying and doesn't go away with updates from Firefox or other addons, so it seams a issue from YouTube+.

Browser Name: Firefox
Browser Version: 54.0.1 (54-Bit) - Issue was also at 52+53
Operating System: Windows 10 1703 / 15063.447
Userscript Manager: Not installed
Problem Description: Subscriptions page cut off on top
Steps to reproduce: Click on the YouTube button after watching a video, subscription page loads and page cut off a little bit on top off the first videos, after reloading the page its fine
Additional details: No Script and uBlock Origins active on YouTube but deactivation doesn't fix the issue

![snip_20170711143847](https://user-images.githubusercontent.com/22057956/28069095-7711d596-6648-11e7-8b56-7fb848d1d7b4.jpg)

**Comment by ParticleCore** [comment] 2017-07-11 13:02
Does the problem occur even with YT+ disabled? I remember having this problem and it was a YouTube only bug.

**Comment by Daisenki** [comment] 2017-07-11 13:16
It does not happen with YouTube+ deactivated, I close the Firefox + delete the cache for testing.

![snip_20170711151028](https://user-images.githubusercontent.com/22057956/28069977-b4c6074c-664b-11e7-811d-27e6f9f8e57b.jpg)

**Comment by ParticleCore** [comment] 2017-07-11 21:17
I have tried to replicate this problem, but never happened. Perhaps it might be a combination of certain settings, can you share yours? No need to include the language file or blacklist if they are in there.

**Comment by Daisenki** [comment] 2017-07-12 08:55
{
  "GEN_BTTR_NTF": true,
  "GEN_SUB_LIST": false,
  "GEN_INF_SCRL": true,
  "GEN_BLUE_GLOW": true,
  "GEN_PPOT_ON": false,
  "VID_END_SHRE": true,
  "VID_DFLT_QLTY": "hd1080",
  "VID_PLST_ATPL": true,
  "VID_PLST_RVRS": true,
  "VID_PLR_ATPL": true,
  "VID_PLR_ALVIS": true,
  "VID_PLR_SIZE_MEM": true,
  "VID_PLR_VOL_LDN": true,
  "VID_POST_TIME": true,
  "VID_VID_CNT": true,
  "VID_DESC_SHRT": false,
  "VID_PPOT_SZ": false,
  "VID_PLR_HTML5": true,
  "BLK_ON": false,
  "floaterX": 2000,
  "floaterY": 2000,
  "firstTime": false,
  "volLev": 50,
  "advOpts": true,
  "blacklist": {},
  "extLang": {},
  "GEN_HDE_CHN_SDBR": false,
  "GEN_HDE_SRCH_SDBR": false,
  "GEN_HDE_RECM_SDBR": false,
  "GEN_HIDE_FTR": false,
  "GEN_CMPT_TTLS": true,
  "GEN_DSB_HVRC": false,
  "GEN_GRID_SRCH": true,
  "GEN_GRID_SUBS": true,
  "GEN_CHN_DFLT_PAGE": "default",
  "GEN_SPF_OFF": false,
  "GEN_REM_APUN": true,
  "GEN_YT_LOGO_LINK": true,
  "GEN_DSBL_ADS": true,
  "GEN_LOCL_LANG": false,
  "VID_LAYT_AUTO_PNL": true,
  "VID_HIDE_DETLS": false,
  "VID_TTL_CMPT": true,
  "VID_HIDE_COMS": "0",
  "VID_PLR_FIT_WDTH": false,
  "VID_PLR_FIT": false,
  "VID_PLR_DYN_SIZE": false,
  "VID_PLR_INFO": true,
  "VID_PLR_HFR": false,
  "VID_VOL_WHEEL": false,
  "VID_PLR_ALACT": false,
  "VID_PLR_VOL_MEM": false,
  "VID_PLR_ANTS": true,
  "VID_PLR_CC": true,
  "VID_PLR_ALVIS_WDTH": "750",
  "VID_SUB_ADS": false,
  "VID_PLR_ADS": true,
  "theaterMode": false
}


{
  "GEN_BTTR_NTF": true,
  "GEN_SUB_LIST": false,
  "GEN_INF_SCRL": true,
  "GEN_BLUE_GLOW": true,
  "GEN_PPOT_ON": false,
  "VID_END_SHRE": true,
  "VID_DFLT_QLTY": "hd1080",
  "VID_PLST_ATPL": true,
  "VID_PLST_RVRS": true,
  "VID_PLR_ATPL": true,
  "VID_PLR_ALVIS": true,
  "VID_PLR_SIZE_MEM": true,
  "VID_PLR_VOL_LDN": true,
  "VID_POST_TIME": true,
  "VID_VID_CNT": true,
  "VID_DESC_SHRT": false,
  "VID_PPOT_SZ": false,
  "VID_PLR_HTML5": true,
  "BLK_ON": false,
  "floaterX": 2000,
  "floaterY": 2000,
  "firstTime": false,
  "volLev": 50,
  "advOpts": true,
  "blacklist": {},
  "extLang": {},
  "GEN_HDE_CHN_SDBR": false,
  "GEN_HDE_SRCH_SDBR": false,
  "GEN_HDE_RECM_SDBR": false,
  "GEN_HIDE_FTR": false,
  "GEN_CMPT_TTLS": true,
  "GEN_DSB_HVRC": false,
  "GEN_GRID_SRCH": true,
  "GEN_GRID_SUBS": true,
  "GEN_CHN_DFLT_PAGE": "default",
  "GEN_SPF_OFF": false,
  "GEN_REM_APUN": true,
  "GEN_YT_LOGO_LINK": true,
  "GEN_DSBL_ADS": true,
  "GEN_LOCL_LANG": false,
  "VID_LAYT_AUTO_PNL": true,
  "VID_HIDE_DETLS": false,
  "VID_TTL_CMPT": true,
  "VID_HIDE_COMS": "0",
  "VID_PLR_FIT_WDTH": false,
  "VID_PLR_FIT": false,
  "VID_PLR_DYN_SIZE": false,
  "VID_PLR_INFO": true,
  "VID_PLR_HFR": false,
  "VID_VOL_WHEEL": false,
  "VID_PLR_ALACT": false,
  "VID_PLR_VOL_MEM": false,
  "VID_PLR_ANTS": true,
  "VID_PLR_CC": true,
  "VID_PLR_ALVIS_WDTH": "750",
  "VID_SUB_ADS": false,
  "VID_PLR_ADS": true,
  "theaterMode": false
}

**Comment by ParticleCore** [comment] 2017-07-14 06:42
I have tried with both the userscript and add-on versions with the settings you provided: Play a video and then click on the YouTube button which redirects to the subscription page. It never gets cut off at the top.

I can only assume that you did not follow the troubleshooting instructions to the letter, so please follow all the steps as requested, including using a blank test profile in Firefox with just YT+ installed. If you did then I will need better instructions to reproduce this problem on my end.

Also please try to see if the same thing happens with Chrome if you can, use the userscript version for that.

Otherwise, I cannot fix something that I can't reproduce on my end.

**Comment by Daisenki** [comment] 2017-07-14 09:33
Thanks for looking into the issue and testing, like I write in my first post, it happens since weeks and get annoying but to be honest its no big deal. I will switch to the new layout in the second you have the Iridium finished or at a working state (Firefox add-on). You can close it with wontfix.

**Comment by q1k** [comment] 2017-07-14 11:31
Try with [portable version of Firefox](https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./Mozilla%20Firefox%2C%20Portable%20Edition%2054.0.1/) and only youtube+ installed.
If the problem is gone, it is something you had installed previously on the main browser that is causing the problem.
Try deleting cache, offline data, and site preferences, and maybe even cookies, then restart the browser. If that doesn't help, create a new clean profile.

**Comment by Daisenki** [comment] 2017-07-14 11:42
I use YouTube and Google only with VPN and need most of the running addons, so I don't risk it to go at YouTube only with YT+, Firefox does not use any cache. The risk for a IP flag is to high with my dedicated IP.

**Comment by ParticleCore** [comment] 2017-07-14 17:32
If you make any progress eventually, please do let me know. For the time being I will close this.

**Closed by ParticleCore** 2017-07-14 17:32 UTC
Labels: help wanted

**Comment by Daisenki** [comment] 2017-07-17 18:41
I found something interesting, two different sizes and the 1277 is the problem of all. Every window use 1262 but only one value is incorrect with 1277, that's why the window is cut off at the top and on the front. But I have no idea why it happens only random and not by everyone...

Is this value a part of your YT+, Firefox or YouTube? If you can fix it, can I help you with more data from the console? 

![snip_20170717202334](https://user-images.githubusercontent.com/22057956/28283996-e833605a-6b2f-11e7-9d50-24b2aedbc7ab.png)

![snip_20170717202606](https://user-images.githubusercontent.com/22057956/28283995-e82b20e8-6b2f-11e7-83bb-30f4472b534a.png)

**Comment by ParticleCore** [comment] 2017-07-17 18:51
I have tested multiple times with those sizes (still using your settings too), but the problem never showed up once.
