### ISSUE TITLE
Option to remove the black background in Theater Mode

### ISSUE THREAD

**Issue by GKid94** [ParticleCore/Particle#502] opened 2017-05-07 01:46 UTC
Browser Name: Chrome

  Browser Version: 58.0.3029.96 (64-bit)

  Operating System: Windows 10 Pro

  Software Type: Tampermonkey

  Software Version: 4.2.7

  Userscript Manager: Tampermonkey

  Userscript Version: 4.2.7
  
  Problem Description: Black background in Theater Mode

  Steps to reproduce: Add an option to remove the black background in Theater Mode

**Comment by ParticleCore** [comment] 2017-05-07 01:50
Duplicate of https://github.com/ParticleCore/Particle/issues/338

Please do not repeat requests.

**Closed by ParticleCore** 2017-05-07 01:50 UTC
Labels: duplicate

**Comment by GKid94** [comment] 2017-05-07 01:58
But I have Tampermonkey not Stylish 😕
