### ISSUE TITLE
Compatability with TubeBuddy

### ISSUE THREAD

**Issue by smithy1294** [ParticleCore/Particle#453] opened 2017-02-07 18:00 UTC
Not sure who's 'fault' it is but when using tubebuddy with your tweak and then going into the 'fill to window' mode the youtube header (the section containing the search bar) stays above the video but the video resizes to the window size meaning you miss the top portion of the video.

Like i said im not sure whos problem it is, personally im guessing its tubebuddys but is there a way on your end you can make sure to always display the video infront of everything else?

Thanks

**Comment by ParticleCore** [comment] 2017-02-07 20:07
Duplicate of https://github.com/ParticleCore/Particle/issues/299

Any fix on YT+ end will be pointless (due to racing conditions) until TubeBuddy stops overriding the masthead default behavior.

**Closed by ParticleCore** 2017-02-07 20:07 UTC
Labels: duplicate

**Comment by mauriciocolli** [comment] 2017-02-07 20:23
If you really want to continue using, you can use this temporary fix in Stylish:
```css
.part_fullbrowser #masthead-positioner {
    z-index: initial !important;
}
```
