### ISSUE TITLE
Main button doesn't react

### ISSUE THREAD

**Issue by Domochevsky** [ParticleCore/Particle#125] opened 2015-11-04 15:19 UTC
Hey,
this issue is with Pale Moon 25.7.3 64bit, a Firefox fork.
The main button in the top right (next to Sign In) does not react when clicked, meaning no options can be accessed.

No further debug info is available, as I don't know how to obtain more.

**Comment by Eisys** [comment] 2015-11-04 17:50
Duplicate of #102

**Comment by Domochevsky** [comment] 2015-11-04 18:45
,,,interesting. So there's not even a chance that this may get fixed, short of doing it myself, hm? :S

**Closed** 2015-11-04 19:05 UTC
Labels: duplicate
