### ISSUE TITLE
Allow to Move Settings From Video Title

### ISSUE THREAD

**Issue by ricksee** [ParticleCore/Particle#444] opened 2017-01-24 06:05 UTC
Is it possible to add a setting to move the settings away from the video title? Can it be moved (autoplay, repeat, take screenshot, etc.) to around the space where add, share and more actions are?

**Comment by ParticleCore** [comment] 2017-01-24 09:26
Duplicate of https://github.com/ParticleCore/Particle/issues/122

**Closed by ParticleCore** 2017-01-24 09:26 UTC
Labels: duplicate
