### ISSUE TITLE
Can't Submit Reason for Restoring to Old YT

### ISSUE THREAD

**Issue by SiberYid** [ParticleCore/Particle#657] opened 2018-01-19 00:24 UTC
Because the bloody message is covering the Submit button, ffs!!!
I have enough grief trying to make stuff work for me without shit like this, surely someone knew about it, do these things get tested?
A whole page on how to Restore Old YT, an option right there in the menu, nothing about buttons being hidden by the message..........
This was an issue, for me, it never dawned on me that the instructions themselves would be what prevented me from following them. They were, though..................

**Comment by ParticleCore** [comment] 2018-01-19 07:02
Duplicate of #550

**Closed by ParticleCore** 2018-01-19 07:02 UTC
Labels: duplicate
