### ISSUE TITLE
youtube, old friend 

### ISSUE THREAD

**Issue by walls50** [ParticleCore/Particle#260] opened 2016-05-11 15:54 UTC
Browser Name: Mozilla Firefox 
Browser Version: 46.0.1
Operating System: windows 7 ultimate edition 64bits
Problem Description: youtube won't load chat, suggested videos and opened video if i use the middle mouse scroll to open in new tabs. if i right click to open in new tab it works 60% of the time and if i click on the video with left click it opens without no problem but i can't multi task. 
i have updated windows, Firefox, flash player shockwave player , quick time, real player, tried all suggestions on your page, nothing works... if i disable the extension it works without no problem. your extension is a really extraordinary example of how smart and useful software should be, it has everything i don't want to go back to magic actions for youtube ( the only reason i was using that is for the scroll mouse volume control because is made like justin bieber's music - for kids! ) 

best regards

**Comment by ParticleCore** [comment] 2016-05-11 16:12
At the moment I can't find anything wrong, I need more information to see if I can replicate the problem.

The guide listed more information which you did not provide:

Are you using the userscript version or add-on version? Which YT+ version are you using? Can you provide a video where this problem occurs? Did you disable all other extensions **except YT+**, restart the browser and see if the problems persist?

A screenshot of the problem might also help a lot.

**Comment by walls50** [comment] 2016-05-11 22:55
using the add-on version 1.2.5. for for saying chat i meant the video comment section ...
did not tried for streaming service 
first gif is when i try to open multiple tabs with scroll button on mouse : https://gyazo.com/5fafc763a6ece8f70bb27cb326913802

when i left click on video and it opens without issues : https://gyazo.com/bf394621a3418ca50f059539ab2d4ac0

when i scroll click a video that does not open and issues goes away after a refresh : https://gyazo.com/2273c342d48479260c9412e65551bf8b

i disabled all extensions and all works awesome except for yt+ ,even after the first extension activated ( and tried this in different order ) yt+ still has the same issues 

i hope this helps

**Comment by ParticleCore** [comment] 2016-05-11 23:20
Thank you, those were very helpful gifs. I am unable to reproduce the problem in both browsers and with all 3 extension versions, none of the tests produced the problem shown in the first gif.

From that first gif I can see that the pages are not finished loading (rotating circle/spinner on the tabs) which means that either something the pages were trying to load has failed or is stuck trying to load, but the strangest thing is that if this was true and being caused by YT+ then it would also occur when you opened the videos like you did on your second gif.

So far I can be certain of either two things:

 1 - This one should be tried first because it is the one I believe to be the cause behind this. Something in your Firefox browser settings is causing this and the best way to confirm this is to try just the YT+ add-on in a new Firefox profile. You can find the instructions for creating a new Firefox profile [here](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles#w_starting-the-profile-manager). This method is the safe way to "reset" Firefox without risking your current configuration. After you have created the new profile and launch the browser with it install just the YT+ add-on and see if the problem still persists.

 2 - Somehow for some very odd reason a possible YouTube update that you have and I don't have yet is causing this problem, if so then I will need you to open a video with the scroll button like you did in the first gif, open the web and browser consoles on that "broken" video page and copy/paste here all messages that might be showing in the consoles. Hopefully there will be error messages showing up. To open both consoles press Ctrl + Shift + K (web console) and Ctrl + Shift + J (browser console).

 3 - As a last resort, to check if this could be a fault with the YT+ type, disable the add-on itself, install the Greasemonkey add-on (if you don't already have), restart Firefox and install the YT+ userscript version which can be found [here](https://github.com/ParticleCore/Particle/raw/master/src/Userscript/YouTubePlus.user.js).

I am sorry for the trouble but since I am unable to reproduce the problem I can only count on your help to find out what might be happening on your end.

**Comment by walls50** [comment] 2016-05-11 23:48
thanks for helping and taking your time the ctrl + shift + j : 

"Handler function NRL_getSecurityInfo threw an exception: TypeError: this.transport is null
Stack: DSC_send@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/main.js:1391:5
NEA_addSecurityInfo@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/webconsole.js:2064:5
NRL_getSecurityInfo@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:265:5
exports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14
NRL_onStartRequest@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:217:5
Line: 1391, column: 5"

ctrl + shift + k :+1: 

'mozHidden' and 'mozVisibilityState' are deprecated.  Please use the unprefixed 'hidden' and 'visibilityState' instead. show_ads_impl.js:209:216
Use of getAttributeNode() is deprecated. Use getAttribute() instead. base.js:167:359

i have no idea what i'm doing ...

**Comment by ParticleCore** [comment] 2016-05-11 23:54
Those are expected messages, unfortunately none of which is related to the problem you are facing. Now there's only 2 more things to try, either the number 3 or number 1 I instructed before. Number 3 should be easier for you to try but if the problem still persists then number 1 will need to be done because I have no other idea as to what could be causing this and what else can be done to find out.

**Comment by walls50** [comment] 2016-05-12 00:42
i removed YT+ and  installed greasemonkey and installed the script nothing changed. i'm sorry. i will still use the extension for the other awesome features and open one video at a time... thanks for your time and patience

**Comment by ParticleCore** [comment] 2016-05-12 00:57
The last thing to try would be the one I suspect is the cause of this problem, if you do decide to give it a try follow the instructions of number 1. These kinds of strange bugs reported here have been mostly related to Firefox settings creating strange problems on the add-on, there was even one where two simple Firefox settings changed to supposedly improve page load times caused a significant page load delay: https://github.com/ParticleCore/Particle/issues/94#issuecomment-144762230 the discovery of this was only possible by following the new profile troubleshooting method, which is why I suggested it to be done first.

If you eventually do try the last option I would like to know how it went, for now I will close the issue.

**Closed by ParticleCore** 2016-05-12 00:57 UTC
Labels: invalid

**Comment by ParticleCore** [comment] 2016-05-12 09:12
Duplicate of https://github.com/ParticleCore/Particle/issues/94
