### ISSUE TITLE
[Feature] Option to disable Autoplay for Background Tabs/Windows

### ISSUE THREAD

**Issue by ldgbc** [ParticleCore/Particle#285] opened 2016-06-29 10:15 UTC
Browser Name: Firefox
Browser Version: 47 stable
Operating System: Windows 10 x64
Software Type: YouTube +
Software Version: v.1.3.3
Userscript Manager: Greasemonkey
Userscript Version: 3.8

Problem Description: Autoplay new tabs/windows

Steps to reproduce:
1. Open any Youtube video
2. Choose another video, Middle Click or Right Click, "Open in new Tabs"
3. New Windows/Tab will be autoplay (due to setting)
4. All opened tab will Start download, buffering and playing (audio, bandwidth issue)

Additional details: People usually open multiple tabs when they have a list of video they want to watch (subscription, being shared, recommended video, etc)

Thank you for making this script.

**Comment by ParticleCore** [comment] 2016-06-29 14:33
Duplicate of #52

**Closed by ParticleCore** 2016-06-29 14:33 UTC
Labels: duplicate
