### ISSUE TITLE
Subscriptions page hanging

### ISSUE THREAD

**Issue by Prostheta** [ParticleCore/Particle#226] opened 2016-02-19 08:13 UTC
Hi - I created an account just to report this. Running 1.1.6 through Tampermonkey in Chrome 48.0.2564.109 m, I get a hang of about 5-6 second when opening the URL:
https://www.youtube.com/feed/subscriptions

Disabling and selectively re-enabling scripts solved the hang, with latest YouTube+ release seeming to be the likely culprit. Beyond this I am unsure as to what other debugging information I can provide. Has anybody else noted this? Can't see anything in the changelog that might suggest anything obvious.

**Comment by ParticleCore** [comment] 2016-02-19 08:16
Try with everything disabled except YT+, if the problem still persists follow the troubleshooting guide: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

I tried the same setup and cannot replicate the problem.

**Comment by Prostheta** [comment] 2016-02-19 09:39
Thanks for the swift reply. Everything was disabled asides from YouTube+ and the window still hangs for a few seconds. I re-checked and this is consistent as stated. Is there anything more specific I can do from this end in terms of diagnosing what is happening?

**Comment by Prostheta** [comment] 2016-02-19 09:40
Videos load and run instantly, it is only the subscriptions page that seems to be hanging up.

**Comment by Eisys** [comment] 2016-02-19 14:59
I have been having this hang for a week or two. For me, YT+ isn't the cause. Even when I disable all addons it happens. But @ParticleCore if you could let us know what could be the cause, then it would be super helpful. While not that big of a deal, it gets really annoying really fast.

**Comment by mauriciocolli** [comment] 2016-02-19 15:18
@Eisys Do you the same browser of the OP?

In Firefox Developer Edition:
https://i.gyazo.com/db350216f1e1b1941805e146a383b3cc.mp4

**Comment by Eisys** [comment] 2016-02-19 15:23
@mauriciocolli  I'm using Chrome Version 49.0.2623.54 beta-m (64-bit)

And my hang is a bit different. I get it when I open subs page, go to another tab and then come back to the subs page.

**Comment by ParticleCore** [comment] 2016-02-19 16:25
This might be caused by two reasons:

1 - Too many subscriptions:

https://www.reddit.com/r/youtube/comments/2zplon/youtube_subscription_page_delayfreezelag/

https://www.reddit.com/r/youtube/comments/3z93fg/1220502_firefox_hangdelay_when_opening_a/

etc.

2 - You have [infinite scroll](https://github.com/ParticleCore/Particle/wiki/Features#infinite_scroll) enabled which is causing the page to load more content automatically each time you are close to the end of the page

Other causes are unknown without more information.

@Prostheta Did you follow the troubleshooting guide I linked? Otherwise I am forced to repeat exactly what is already instructed in that guide.

@Eisys Your case could be related to cause number 1

**Comment by Eisys** [comment] 2016-02-19 17:38
Thank you for the insight. I do have 120 subscriptions. 

I just tried it with Firefox, logged in with my account and it doesn't happen. Same with Edge browser.
Guess it's just a Chrome thing then.

**Comment by ParticleCore** [comment] 2016-02-19 19:57
@Eisys To confirm this being a too many subscriptions issue I'd suggest making a dummy account, subscribe to 20 odd channels and see if the issue persists with that amount of subscriptions. If it persists then it is most likely something else (I remember reading something about ABP causing it, but I think it was fixed way back then), if it doesn't persist then it was the cause of the problem and perhaps sending YouTube or Chrome your feedback might hurry them with a fix.

**Comment by Eisys** [comment] 2016-02-19 22:22
I actually tried that earlier with an old YT account which has 26 subs. I was getting inconsistent results but I just tried it again and hangs every time. 
Also tried it on my laptop which has release version of chrome and it still happens. I thought perhaps the fact mine is beta had something to do with it.

And I don't use ABP, just uBlock Origin but this shouldn't matter since it still happens with all addons disabled and even in incognito mode.

**Comment by ParticleCore** [comment] 2016-02-20 14:35
@Eisys It sounds like it is related to any feed pages. To find out what is causing it, if it is some network communication you might be able to track down the culprit in the console so open the console, go to the Network tab, open any of the problematic pages and see if any communication is made **before or after** the hang occurs.

**Comment by Eisys** [comment] 2016-02-20 15:44
Oh boy. There is alot going on in that console.

There is one error I get right when the hang starts: http://prntscr.com/a5qmnt
Resource interpreted as Document but transferred with MIME type text/javascript: "https://s.ytimg.com/yts/jsbin/player-en_US-vfldIygzk/base.js".
The other errors are there with from the start.

This is the console after I refresh the page and it finishes loading:
http://prntscr.com/a5qnsk

This is the console during the hang:
http://prntscr.com/a5qob6

And this is what it's like after the hang:
http://prntscr.com/a5qomn

It seems the problem is that base.js thing. If I hover over it, it has the same URL as the error below.

I get the same kind of thing on my laptop.

**Comment by ParticleCore** [comment] 2016-02-20 16:23
Those console messages are normal, the first group is google chrome-cast's lazy coding that [has been going unfixed for quite some time](https://code.google.com/p/google-cast-sdk/issues/detail?id=309).

The other one blocked by client is your ad-blocker doing its work as it is suppose to.

The last one I have exactly the same, so it doesn't appear to be the cause of it, at least the "Resource interpreted..." message cause isn't.

Next and final step that I would try is to block the files that appear to be the cause of this problem, so use your uBlock to block the base.js link and try again (expect YouTube looking pretty ugly or working terribly, what you want is see if the hanging persists), if it persists keep blocking other files etc.

More than this I can't help because I don't have enough knowledge and because I cannot replicate it, this is not related to YT+ so it is also pointless to continue with this in this issue tracker since it is unrelated to the software being developed here.

**Comment by Eisys** [comment] 2016-02-20 16:36
So I blocked the base.js URL and it is now fixed. No more hangs.
And youtube still looks normal so all is well.

Thank you so much for all the help.

**Comment by ParticleCore** [comment] 2016-02-21 17:57
I will close this for now, @Prostheta if you still need help please follow the troubleshooting guide first.

**Closed by ParticleCore** 2016-02-21 17:57 UTC
Labels: invalid
