### ISSUE TITLE
"Player always visible when reading comments" isn't working

### ISSUE THREAD

**Issue by Maheshchiramure** [ParticleCore/Particle#248] opened 2016-04-05 03:32 UTC
Settings > Video > Player always visible when reading comments

Unchecked it, saved the settings, but the Player won't leave me alone. Why must be that ?

**Comment by ParticleCore** [comment] 2016-04-05 06:09
Please provide more information than just that, it is not sufficient for me to replicate or understand the cause of this problem. Follow the reporting guide: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by ParticleCore** [comment] 2016-04-07 09:32
I will close this for now, if you are still having this problem follow the instructions in the previous reply.

**Closed by ParticleCore** 2016-04-07 09:32 UTC
Labels: invalid
