### ISSUE TITLE
Player will not pause

### ISSUE THREAD

**Issue by HerrKaha** [ParticleCore/Particle#172] opened 2015-12-21 10:42 UTC
Browser Name: Firefox
Browser Version: 43.0.1
Operating System: Win10 64 bit
Software Type: Userscript with Greasemonkey
Software Version: 0.9.2

When I pause the video and go to another tab for a while and come back and play the video again, the buffering animation stays on the video. Then I can not pause the video again. When I click on the video a play icon appears over the buffering .gif but nothing happens. This is quite rare and I don't know exactly what causes it. I think that that the video has to be fully loaded to the end for this to happen, but I'm not sure. Allso when I come back to the video from another tab from my browser the video is paused and totally black. I think that this is also very important! For it to turn black you have to be on another tab for a minute or two. 

I can only pause the video again if I click on the brogress bar and change the time of the video. After that 

I allso have autoplay and fullbrowser mode enabled. 

Here are some pictures of what it looks like:

Video when playing with the buffer image
![screenshot 2015-12-21 12 22 57](https://cloud.githubusercontent.com/assets/16361388/11928918/cfb1aef2-a7df-11e5-92c5-e6d7f53c03d8.png)

Video when i try to pause the video and a play button image pops up over the buffer image but nothing happens
![screenshot 2015-12-21 12 23 01](https://cloud.githubusercontent.com/assets/16361388/11928921/d65056fa-a7df-11e5-9e62-da1b648b9c61.png)

Black screen when I come back fron another tab
![screenshot 2015-12-21 12 39 07](https://cloud.githubusercontent.com/assets/16361388/11928926/da5fafe8-a7df-11e5-97f4-03332cfff1b6.png)

**Comment by ParticleCore** [comment] 2015-12-21 10:57
Users without YT+ have been reporting this problem as well, exact same behavior: https://www.reddit.com/r/youtube/comments/3xkw6x/videos_wont_pause/

I cannot find in YT+ anything that could be causing this problem.

This sounds like what happens when the stream signature times out, except instead of trying to renew the signature it fails to do so. Basically every single video you watch is served to you with a signature that lasts for a certain time, past that time the stream links you had no longer work and they need to be renewed.

I haven't been able to replicate the issue once, every time I pause the video and resume a long time after the player correctly renews the streams correctly and resumes playback, no failure occurs.

A suggestion I have is for you to disable every single add-on except YT+ and see if the problem still persists, if it does then disable YT+ as well and see if it happens again.

Also report the problem to the YouTube team via the "Send feedback" link found at the bottom of every YouTube page, if it is a problem on their end they might be able to fix it quickly.

About the black screen when changing tabs, that is a Firefox problem and I get that a lot too. There's nothing I can do to fix this one, it is a browser problem, it is failing to paint the media when the tab becomes active.

For now there is nothing I can do so I will close this issue. However I would ask for you to be alert when the pause/buffering issue happens again. When it does open the browser console (`Ctrl + Shift + J´) and see if there's any messages posted on it, any errors or warnings showing. If there are post them here in this thread, it will be used to continue monitoring this problem.

**Closed by ParticleCore** 2015-12-21 10:57 UTC
Labels: wontfix

**Comment by HerrKaha** [comment] 2015-12-21 11:01
Thank you! I will report this to the youtube team and I'll keep an eye on the progress.

**Comment by HerrKaha** [comment] 2015-12-21 11:51
The issue popped up again and from browser console I see this: 
![screenshot 2015-12-21 13 50 31](https://cloud.githubusercontent.com/assets/16361388/11930172/cd19dc1e-a7e9-11e5-955e-8a2ccac6eeef.png)

**Comment by ParticleCore** [comment] 2015-12-21 13:12
For the `http://localhost:27275/command` error it seems it is related to Avast's Site Correct service: https://forum.avast.com/index.php?topic=100948.0

I can't tell if it is what is causing problems on YouTube because it does not show the source of the error, however you can try disable Avast and all of its services, plugins and extensions, restart and see if the problem shows up again. It wouldn't be surprising if an Anti-virus was causing problems with YouTube again. Norton, for example, has a long history of conflicts.

If the YouTube problem lies with `NetworkError: A network error occurred` then I am afraid there's nothing that can be identified because no further information is provided, including the source of the problem.

If disabling Avast does not solve the issue then my previous suggestions still stand, try with all add-ons disabled and with all disabled except YT+.

Just out of chance, if you happen to be using a VPN/Proxy or any form of traffic obfuscation try turning it off. It is a long shot, but it could be causing this issue as well.

**Comment by ParticleCore** [comment] 2015-12-21 13:41
Also I have removed your first 3 screenshots for your protection because I noticed they contained information that might be private.

**Comment by HerrKaha** [comment] 2015-12-21 14:31
I tried to disable Avast and and all of it's stuff... didn't seem to help. (did not restart the whole computer tho.. should I?) I disabled all other add-ons aswell and still got the problem. At least I can consistently reproduce the problem now...

BTW, thanks for deleting those, I didn't notice that myself.

**Comment by ParticleCore** [comment] 2015-12-21 14:45
I doubt you need to restart, for now it looks like you have ruled out the possibility of this being caused by something you have installed on your browser.

One last thing you could try is to make a new test profile to rule out any browser setting that might have been changed and could be affecting YouTube. Another user had a problem that was being caused by his browser settings, the new profile helped finding that out: https://github.com/ParticleCore/Particle/issues/94#issuecomment-144751359

To create a new test profile follow these instructions: https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles#w_starting-the-profile-manager

Don't install any extension, try to replicate the problem again since you can consistently reproduce it. If you cannot then it is very likely that a browser setting (or more) was causing the problem and to find out which you will have to go through a boring process or you can just use the new test profile as your default.

**Comment by HerrKaha** [comment] 2015-12-21 15:52
I did make a test profile and it worked. But what i noticed was that the problem was still there for about 3 seconds. During that time I could not pause the video but after those seconds the buffering image went away and everything was normal again... So the problem is somewhere in my settings

**Comment by ParticleCore** [comment] 2015-12-21 16:20
If that is the case and you want to discover which setting (or more) is causing it you can follow these instructions: https://github.com/ParticleCore/Particle/issues/94#issuecomment-144754870

**Comment by ParticleCore** [comment] 2015-12-22 01:30
If you happen to find the cause of this issue or make any sort of progress do let me know, it might help other users in the future.

**Comment by ParticleCore** [comment] 2016-01-04 06:43
Just an update, it looks like this issue was related to Firefox and has been fixed in FF 43.0.3:

>On some Windows configurations, improve the decoding of some videos on YouTube ([1233970](https://bugzilla.mozilla.org/show_bug.cgi?id=1233970))


https://www.mozilla.org/en-US/firefox/43.0.3/releasenotes/
