### ISSUE TITLE
Option to hide the “related videos” sidebar and video wall.

### ISSUE THREAD

**Issue by dotdapple** [ParticleCore/Particle#179] opened 2015-12-31 05:32 UTC
(When I say video wall, I mean the screen that comes up at the end of a video.)

Thanks for the consideration!

**Comment by ParticleCore** [comment] 2015-12-31 05:53
Duplicate of https://github.com/ParticleCore/Particle/issues/29

**Closed by ParticleCore** 2015-12-31 05:53 UTC
Labels: duplicate
