### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MacgyverJohnson** [ParticleCore/Particle#402] opened 2016-11-16 12:10 UTC
Hi there @ParticleCore 
Totally love Youtube+
Would it be possible if scrolling was allowed on full browser mode? or auto hide youtube search bar when video is playing in theatre mode? This is possible and still working on Youtube Center....
thanks

**Comment by Eisys** [comment] 2016-11-16 14:58
[These 2 scripts allow the top bar to be hidden](http://i.imgur.com/RUjawAQ.png)

https://gist.github.com/Yonezpt

**Comment by MacgyverJohnson** [comment] 2016-11-16 17:48
Thanks @Eisys for the quick reply....
headerhider is working fine but I think mousehideytheader is not (i need both of them)
Problem with mousehideytheader...it by itself hides part of the video when it is supposed to just toggle the top bar visibility on mouse hover....
![yt-iloveimg-compressed](https://cloud.githubusercontent.com/assets/17729946/20358618/b6c27d78-ac56-11e6-889e-ee38f502b656.gif)
My screen resolution:1366x768
firefox 49 greasemonkey 3.9 beta2

**Comment by Eisys** [comment] 2016-11-16 18:09
Yeah they're not meant to work together so you're gonna have to choose only one.

If the animation speed of mousehideytheader is too slow or the mouse detection distance too high then here's a version with them both changed: http://pastebin.com/d0eGsreX
You can compare the original and this version if you want to make your own changes.

Or perhaps disable the header alltogether with Stylish, only on the /watch page, like I have, and use a new YT tab to search for things. Just food for thought.

I didn't make those scripts so I can't help you any further since I don't know much about how they exactly work.
I'm about 95% sure that Yonezpt is ParticleCore's other account and he made them so wait for him to reply, perhaps he'll have some more insight.

**Comment by ParticleCore** [comment] 2016-11-16 19:14
Duplicate of https://github.com/ParticleCore/Particle/issues/278

As for the scripts, looks like he fortunately managed to work it out on his own.

**Closed by ParticleCore** 2016-11-16 19:14 UTC
Labels: duplicate
