### ISSUE TITLE
Disable HFR 60fps doesn't work on all videos - Also, ads only on subscribed channels, sometimes doesn't work

### ISSUE THREAD

**Issue by The-Euphoria** [ParticleCore/Particle#481] opened 2017-04-01 13:09 UTC
Hi Particle, I have a couple of issues with YT+ I'm hoping you might help me with, please.

Browser Name: Chrome
Browser Version: 57
Operating System: Win 10 x64 Pro
Software Type: YT+ Extension from Chrome store
Software Version: 1.8.3
Problem Description: _Disable HFR 60fps_ - The box is checked, but it only seems to work on some videos. Example: one of subbed channels: _TopeREC TV_, his videos for me still play in 60fps and show the options in the player settings for 720p60 and 1080p60. There have been a few other videos too that still showed the 60fps option. I tried testing this on my partner's laptop as well, and the issue persists.

Second issue: _Enable advertisements only in videos from subscribed channels_ - Again, this feature seems to work sometimes for me, but then randomly stops working and video ads appear on non-subbed channels. 

Steps to reproduce: Try playing a video on TopeREC TV channel, his videos always seem to still show as 60fps for me.
As for the ads, not sure how to reproduce this as it seems random, plus ads don't always play on the same videos every time.

If I'm missing some info you need, my apologies, just let me know and I'll update my post.

Thanks,
regards 

Edit - Screenshot
![untitled](https://cloud.githubusercontent.com/assets/18595972/24579068/bd7c2b04-16f6-11e7-9a44-8d8715f2f3c3.png)

**Comment by ParticleCore** [comment] 2017-04-01 14:07
Please don't couple issues, it will make it harder for other users to find them if they are all together in one thread.

As for the 60HFR not always working, this has already been discovered before here: https://github.com/ParticleCore/Particle/issues/435#issuecomment-279917257

And as a result of that discovery I already updated the wiki with the relevant information regarding this situation:

>HFR (High Frame Rate) streams will be disabled when possible, there are cases when this is not possible, please read issue #435

https://github.com/ParticleCore/Particle/wiki/Features#hfr_off

However, after checking the videos you suggested to confirm what I said, I discovered that the new method of delivering streams that YouTube is now using has been updated and they are _finally_ including the non HFR streams along with the other ones:

`id="133" codecs="avc1.4d400c" width="426" height="240" frameRate="30"
id="134" codecs="avc1.4d401e" width="640" height="360" frameRate="30"
id="135" codecs="avc1.4d4014" width="854" height="480" frameRate="30"
id="160" codecs="avc1.4d400b" width="256" height="144" frameRate="30"
id="136" codecs="avc1.4d4016" width="1280" height="720" frameRate="30"
id="137" codecs="avc1.640028" width="1920" height="1080" frameRate="30"
id="298" codecs="avc1.4d4020" width="1280" height="720" frameRate="60"
id="299" codecs="avc1.64002a" width="1920" height="1080" frameRate="60"`

Which means that, hopefully, it will be possible to make the HFR work with the new method.

As for the ads playing on some of the non-subscribed channels, I am sorry but I cannot work with something that I cannot reproduce. I'd suggest for you to follow the troubleshooting guide to see if you can find a culprit that might be causing this problem (another extension, a browser setting, etc.) https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

Or find a way to reproduce it so that I can check what is happening on my end and see if I can find a solution for that.

But when you have anything to work on the ads problem, please open as a new issue instead just for the ads problem, this is better so that this one remains just for the HFR issue and the other just for the ads problem.

I will try to fix the HFR as soon as I can.

**Comment by ParticleCore** [comment] 2017-04-01 14:12
Because this issue is the same as the one I linked before, I will use that one as the main issue and this will be a duplicate of it, this is just for keeping things organized. If you wish to follow up on the issue just go to the linked issue below and press the subscribe notifications button on the right sidebar to receive any updates on it.

Duplicate of https://github.com/ParticleCore/Particle/issues/435

**Closed by ParticleCore** 2017-04-01 14:12 UTC
Labels: duplicate

**Comment by The-Euphoria** [comment] 2017-04-01 14:25
Oh sorry, I searched closed issues for HDR but somehow completely missed that thread, my bad. Thank you for the info, and hopefully your new method for disabling 60fps works out 👍

As for the ads, yeah I pretty sure there wouldn't be much you could do without more info. I'll make a note of any video URLs that caused issues and let you know.
Also, I have tried without any other extensions and Chrome defaulted to factory settings, but the issue still occurred on a few videos.

Thanks again,
regards

**Comment by ParticleCore** [comment] 2017-04-01 20:00
I noticed you haven't subscribed to the other issue, so I thought I'd let you know. Version 1.8.4 comes with a fix for this problem, let me know if it works for you too. And thanks for this, otherwise I don't think I would remember to check this again to find out if there was anything changed.
