### ISSUE TITLE
Skip ad button is gone when Youtube Plus actived

### ISSUE THREAD

**Issue by hamkah2c** [ParticleCore/Particle#57] opened 2015-08-18 13:04 UTC
Browser Name: Chrome

Browser Version: 44.0.2403.155 m

Operating System: Win7 64 bit

Software Type: Extension

Software Version: 0.4.9

Problem Description: When Loading video, video ads is loading, but, the button for skipping ads is gone. I have disable all my extension except Youtube Plus, but the button is still gone.

Steps to reproduce: ...

Additional details: My youtube language is English (UK)
And here my setting:
 {
  "BLK_ON": false,
  "GEN_BLUE_GLOW": true,
  "GEN_BTTR_NTF": true,
  "GEN_CHN_DFLT_PAGE": "videos",
  "GEN_CMPT_TTLS": false,
  "GEN_DSBL_ADS": true,
  "GEN_DSB_HVRC": true,
  "GEN_GRID_SRCH": false,
  "GEN_GRID_SUBS": true,
  "GEN_HDE_CHN_SDBR": false,
  "GEN_HDE_RECM_SDBR": false,
  "GEN_HDE_SRCH_SDBR": false,
  "GEN_HIDE_FTR": true,
  "GEN_INF_SCRL": true,
  "GEN_REM_APUN": true,
  "GEN_SDBR_ON": false,
  "GEN_SPF_OFF": false,
  "GEN_SUB_LIST": true,
  "GEN_YT_LOGO_LINK": true,
  "VID_DESC_SHRT": true,
  "VID_DFLT_QLTY": "large",
  "VID_END_SHRE": false,
  "VID_HIDE_COMS": "0",
  "VID_HIDE_DETLS": false,
  "VID_LAYT_AUTO_PNL": true,
  "VID_PLR_ADS": false,
  "VID_PLR_ALVIS": false,
  "VID_PLR_ANTS": false,
  "VID_PLR_ATPL": true,
  "VID_PLR_CC": false,
  "VID_PLR_DASH": false,
  "VID_PLR_DYN_SIZE": true,
  "VID_PLR_FIT": true,
  "VID_PLR_FIT_WDTH": "1000px",
  "VID_PLR_INFO": false,
  "VID_PLR_SIZE_MEM": true,
  "VID_PLR_VOL_MEM": false,
  "VID_PLST_ATPL": true,
  "VID_PLST_RVRS": true,
  "VID_PLST_SEP": true,
  "VID_POST_TIME": true,
  "VID_SDBR_ALGN": "1",
  "VID_SUB_ADS": false,
  "VID_TTL_CMPT": false,
  "VID_VID_CNT": true,
  "VID_VOL_WHEEL": false,
  "advOpts": false,
  "blacklist": {},
  "frameStep": false,
  "fullBrs": false,
  "lightsOut": false,
  "plApl": false,
  "plRev": false,
  "theaterMode": true,
  "volLev": 50
}

Screenshot: ![image](https://cloud.githubusercontent.com/assets/8862875/9330431/8addd390-45e3-11e5-9e41-d29dccb5770c.png)

**Comment by ParticleCore** [comment] 2015-08-18 14:48
Thank you for bringing this to my attention, I have confirmed the issue on my side and will try to push a fix as soon as possible.

**Comment by ParticleCore** [comment] 2015-08-18 16:49
I have released a fix for this issue, let me know if it works correctly now.

**Closed** 2015-08-18 16:48 UTC
Labels: bug

**Comment by hamkah2c** [comment] 2015-08-19 13:53
Yes, this work correctly now, but there is new bug about text ads
do I have open new issue?

**Comment by ParticleCore** [comment] 2015-08-19 14:31
If you could, open the new issue with a screenshot showing this problem.

**Comment by ParticleCore** [comment] 2015-08-19 14:59
There's no need, I managed to find the fix the problem in the meantime. Will update the new version and let you know when it is ready.

**Comment by ParticleCore** [comment] 2015-08-19 15:06
Version 0.5.2 is available for update, let me know if the overlay ads issue has been fixed now.

**Comment by Eisys** [comment] 2015-08-19 18:20
Hey @ParticleCore , I didn't want to make a new issue, so Im gonna ask here. 
Is there an update checker in the addon? It seems you're updating quite often and it'd be nice to be up to date all the time. Or is it just easier to come on this site and check the latest version?

**Comment by ParticleCore** [comment] 2015-08-19 18:32
@Eisys No, due to too many complications I've opted not to add such feature for now. If you are using the Firefox Add-on version then I am sorry, but you will have to check for updates manually by visiting the page, until the add-on is reviewed auto-updates are disabled by Mozilla.

For the other options, userscripts are usually the fastest to update, but both userscript managers and the Chrome extension manager have a built in feature to check for updates, so it shouldn't suffer too much of a delay.

**Comment by hamkah2c** [comment] 2015-08-20 00:22
Yup, now it's perfect :D
Thank you for this great extension :+1:
