### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by MisterKain** [ParticleCore/Particle#437] opened 2017-01-14 13:46 UTC
Would've been awesome if your add-on supported an automatic page-wide youtube videos with ability to scroll down into comments section without minimizing feature just like in Youtube HighDefinition mozilla addon. The problem with mentioned add-on is that its pretty buggy and auto play stops working in it, if you can add same feature to your add-on you'll get my positive review and probably some from my friends too.

**Comment by ParticleCore** [comment] 2017-01-14 13:56
Duplicate of https://github.com/ParticleCore/Particle/issues/58

Also, while it sounds good to use positive reviews as an "incentive" for developers to create something a user wants, it is actually perceived as coercion more than anything. It is alright to request features, but to say that you will give a positive review if the feature is introduced sounds like you will give a negative review if the developer does not do what you want.

**Closed by ParticleCore** 2017-01-14 13:56 UTC
Labels: duplicate
