### ISSUE TITLE
Material Layout pop-up position

### ISSUE THREAD

**Issue by Gittyperson** [ParticleCore/Particle#588] opened 2017-09-27 10:46 UTC
On my system, it always appears on top of the buttons that disable the new layout, making them difficult -if not impossible- to click. Any chance it can be made movable?
YouTube keeps reverting me to the new layout, but that's another issue.

![01](https://user-images.githubusercontent.com/7165208/30909494-f9a1baac-a389-11e7-9f27-c3a08f72221d.jpg)

![02](https://user-images.githubusercontent.com/7165208/30909495-f9a46130-a389-11e7-9e70-b4532196c93e.jpg)

**Comment by Eisys** [comment] 2017-09-27 12:01
Duplicate of #550

**Comment by ParticleCore** [comment] 2017-09-27 15:48
Duplicate of #550

**Closed by ParticleCore** 2017-09-27 15:48 UTC
Labels: duplicate
