### ISSUE TITLE
Particle not works with Material Design

### ISSUE THREAD

**Issue by rehannali** [ParticleCore/Particle#576] opened 2017-09-09 18:55 UTC
Google is releasing material design for youtube and I tried it, there is no support for particle on material design. I wanted to know if Particle does support to material design or we have to live with out it.

**Comment by ParticleCore** [comment] 2017-09-09 18:59
Duplicate of https://github.com/ParticleCore/Particle/issues/572

**Closed by ParticleCore** 2017-09-09 18:59 UTC
Labels: duplicate
