### ISSUE TITLE
[feature] show ratings preview below video thumbnails in search results and playlist

### ISSUE THREAD

**Issue by alexchandel** [ParticleCore/Particle#265] opened 2016-05-31 18:10 UTC
Showing the ratings of videos in the search results or play queue is useful, and can help one avoid sponsored content, clickbait, and all-around bad videos.

I notice this is a popular request (#259, #75, #244). Would you leave this open until it can be implemented?

There's already one implementation by http://ratingspreview.com/, but running this with Particle results in inordinately high memory usage. It simply draws a ratings bar under each video thumbnail, similar to the ratings bar Youtube itself draws under the main video. Its source could probably be copied or used as inspiration for a Particle implementation.

**Comment by ParticleCore** [comment] 2016-05-31 19:09
Duplicate of https://github.com/ParticleCore/Particle/issues/75

Sorry, but as it is explained in the [wiki](https://github.com/ParticleCore/Particle/wiki), extension descriptions and the linked requests, due to time and framework limitations I am unable to accept any more feature requests.

**Closed by ParticleCore** 2016-05-31 19:09 UTC
Labels: duplicate

**Comment by alexchandel** [comment] 2016-06-01 20:29
This has been repeatedly requested, and is objectively useful, working around a design flaw in Youtube. You should be interested in it. Even if you can't act on it due to time limitations, you should leave an issue open marking that the deficiency exists.
