### ISSUE TITLE
Issues with live youtube stream

### ISSUE THREAD

**Issue by vzjrz** [ParticleCore/Particle#49] opened 2015-07-28 23:59 UTC
Browser Name: Firefox

Browser Version:  39.0

Operating System: Windows 7

Software Type: Brand new profile

Software Version: YouTube + 0.3.9

Userscript Manager: Greasemonkey

Userscript Version:  3.3

Problem Description: No chat and '`</li>` ' on 5254 watching

Steps to reproduce: New profile, install greasemonkey, install youtube + userscript, check 'Disable hovercards', log into youtube (you must be logged into youtube), visit any live stream.
This channel should have some live streams: https://www.youtube.com/user/dota2

![http://i.imgur.com/H6ZxJZs.png](http://i.imgur.com/H6ZxJZs.png)

**Comment by ParticleCore** [comment] 2015-07-29 00:22
The chat is working correctly after following the exact steps you described:

![image](https://cloud.githubusercontent.com/assets/9222661/8947148/e8792620-3586-11e5-9b50-b73a939b8a01.png)

I assume that you followed the troubleshooting steps: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

But I have to ask anyway since I am unable to reproduce it:

 - Are you running just greasemonkey and YT+ or do you have more userscripts or add-ons installed?

 - Does the problem persist with YT+ disabled?

The problem description about the element on line 5254 is not very clear, could you specify?

Also it is possible that this is a conflict with a recent YouTube change that you might have received, but I haven't yet, so if that is the case I might be unable to replicate the issue until I receive the change as well.

**Comment by ParticleCore** [comment] 2015-07-29 00:26
Also, are you using the Flash player or HTML5 player? Because YT+ supports only the HTML5 player.

**Comment by vzjrz** [comment] 2015-07-29 00:55
This is with a brand new profile with no other addons installed using the html5 player. Once greasemonkey, or youtube+ , or check 'Disable hovercards' is disabled the problems goes away. Made a new google/youtube account and the problem still persists.
username: test9879070977@gmail.com
password: 859529az

**Comment by ParticleCore** [comment] 2015-07-29 01:26
I have managed to fix the watching bug, it will be released with the next version.

Now the problem with the chat, it is very strange that it starts working when you have hovercards disabled. This setting is part of the YouTube library and as such it shouldn't cause conflict with anything else apart from the hovercards, especially not with the chat box, unless there is something wrong with it, in which case the fix will have to be on their side.

Does anything show in the console when the problem occurs? Press F12 to open the console panel, see if there is any error or warning in there that might indicate more information.

Once again, this might be a YouTube change that I have not yet received, so until that happens it will be practically impossible for me to find out what is happening without your help.

**Comment by ParticleCore** [comment] 2015-07-29 21:17
I have released version 0.4.0, does the problem persist with that version?

If it does, can you check the web console for any warning or error?

**Comment by vzjrz** [comment] 2015-07-29 21:29
Problem still here on 0.4.0. No errors or warnings in the web console. Are you sure you're testing youtube logged in? The bug only shows up when you're logged in.

**Comment by ParticleCore** [comment] 2015-07-29 21:36
The screenshot I posted shows that I was logged in, otherwise it would ask in the chat box to sign in. I've tried with Firefox 39, Firefox Nightly and Chrome 44, all with new profiles, logged in and out, with hovercards disabled and enabled, the problem never occurs.

Does it also happen if you use the add-on version? https://addons.mozilla.org/en-US/firefox/addon/youtube-plus/

Also could you test the issue with Firefox Nightly or Chrome?

**Comment by vzjrz** [comment] 2015-07-29 22:40
Tried the addon version and the error still occurs on both Firefox 39 and Firefox Nightly but doesn't occur on chrome. Then I tried it on a different pc and I couldn't reproduce the bug. I guess it's safe to assume the problem is on my end. Thanks for your help though.

**Comment by ParticleCore** [comment] 2015-07-29 22:48
This is very strange, it seems to be restricted to the Firefox platform and only in that computer, I've never heard of anything similar before. I will then close this issue for now, if I happen to come accross it I will open it again or if you happen to find out what is causing this peculiar issue.

Just as a precaution, I'd like to suggest you to run a deep virus scan, get [Malwarebytes](https://www.malwarebytes.org/) and [AdwCleaner](https://toolslib.net/downloads/viewdownload/1-adwcleaner/), run them and see if your computer is not infected with any malware or virus. It is a long shot, but it is not impossible for this to be caused by malware.

**Closed by ParticleCore** 2015-07-29 22:48 UTC
Labels: bug
