### ISSUE TITLE
Frame by frame inconsistant?

### ISSUE THREAD

**Issue by bobcatangel** [ParticleCore/Particle#275] opened 2016-06-18 03:40 UTC
Browser Name: Chrome

Browser Version: 51.0.2704.103 m

Operating System: Windows 10

Software Type: Youtube Plus

Software Version: 1.3.2

Problem Description: The frame by frame function only works some of the time on different videos. I'm an animation student, so going frame by frame helps a lot, but it doesn't seem to work when I want it to, and it reverts to using the Youtube shortcut of 5 seconds at a time, regardless of wheter I hold dow the shift key or whether the icon is on. 

Steps to reproduce: I experimented with many different videos. The one video I wanted to use frame by frame on was this one and it wouldn't work. https://www.youtube.com/watch?v=iAykOz1gWi4 
I tried using it with this one and it worked just fine. https://www.youtube.com/watch?v=hzO5VhP32mE
Is there any reason why it only works on certain videos?
Additional details:
 ![problem](https://cloud.githubusercontent.com/assets/20008591/16168819/58e6c888-34e4-11e6-956c-50cbed180855.jpg)
From this screemshot, you can  see the 5+ forward symbol on the video, but the frame by frame option is on while I was holding shift.

**Comment by mauriciocolli** [comment] 2016-06-18 05:07
It happens to me too, and analyzing more I discover that when a video don't show that `@<fps>` on the Resolution field, in the Stats for nerds info, this function doesn't work:
![edited](https://cloud.githubusercontent.com/assets/13389907/16168930/c627186a-34f0-11e6-82d9-9f53d0336f41.png)

So as the YouTube API doesn't have a method to get the fps, and some random videos doesn't contain that info even in the Stats for Nerds, the method that this extension use doesn't work, and then fallback on the default behavior.

Well, I think that's the reason, @ParticleCore What you think?

**Comment by ParticleCore** [comment] 2016-06-18 11:17
The cause of this problem is YouTube not labeling some streams correctly, such as the pinocchio example. The FPS value is there and YT+ is working as expected, the problem is YouTube is saying that the video has 1 FPS instead of 15 (which is the lowest possible in YouTube), so YT+ ignores it. I will work on a fix for this today and try to release it as soon as I can.

**Closed** 2016-06-18 12:25 UTC
Labels: bug

**Comment by ParticleCore** [comment] 2016-06-18 12:30
Version 1.3.3 contains a workaround for this problem, let me know if it works for you as well.

**Comment by bobcatangel** [comment] 2016-06-18 18:24
Yep, everything seems to be working now. Thank you so much for the quick response!
