### ISSUE TITLE
“Default channel page” doesn't work, when I'm in any subscribed or unsubscribed channel.

### ISSUE THREAD

**Issue by Piter432** [ParticleCore/Particle#233] opened 2016-02-25 10:43 UTC
Looks like “Default channel page” feature doesn't work, when I'm already in any YouTube channel, no matter I subscribed that channel or not. I think it's a bug.

**Comment by ParticleCore** [comment] 2016-02-25 13:06
This is an intended behavior:

>This feature only works outside the channel page.

https://github.com/ParticleCore/Particle/wiki/Features#channel_page

**Comment by Piter432** [comment] 2016-02-26 20:54
I just discovered that this feature doesn't work also when when I'm in YouTube's videos page/watching any video. I guess this is also an intended behavior? :)

**Comment by ParticleCore** [comment] 2016-02-26 21:18
Definitely not, can you give me examples of where this is not working please?

**Comment by Piter432** [comment] 2016-02-26 21:30
First two example videos from some channels I subscribed, and this feature doesn't work.
- https://www.youtube.com/watch?v=vjteJnoq-CA (Zemalf's XCOM 2 let's play in English)
- https://www.youtube.com/watch?v=ss6nH7kSZS4 (SargeThePlayer's Resident Evil 0 HD Remaster let's play in Polish)

---

And here's an example video, where this feature doesn't work also on channels that I don't subscribe:
- https://www.youtube.com/watch?v=Rd6cPXQAXrA (AngryJoe's review of Layer of Fear video game)

**Comment by ParticleCore** [comment] 2016-02-26 21:32
Do you mean it doesn't work in the comments section, correct? Because the video's channel link is being changed correctly, only the names in the comments are not.

**Comment by Piter432** [comment] 2016-02-26 21:41
>Do you mean it doesn't work in the comments section, correct?
Hmm, looks like it doesn't work also in the comments section instead only after clicking 3 horizontal bars next to YouTube's logo and hovering to any subscribed channel when I'm in YouTube's video page/watching any video. However, I've set to hide the comments section by default.

**Comment by ParticleCore** [comment] 2016-02-26 21:42
I think I can only see this problem restricted only to the comment section, if you find somewhere else where it is not working (except the channel pages) let me know. I will try to push a fix for this when I get  home.

**Closed** 2016-02-27 12:06 UTC
Labels: enhancement

**Comment by ParticleCore** [comment] 2016-02-27 12:12
This should be fixed in 1.1.8 and also this feature now includes links inside the channel pages. There were some problems with including the channel pages when I first developed it, but they seem to be gone now. Let me know if it works for you as well.

**Comment by Piter432** [comment] 2016-02-27 12:56
The feature works fine, for now. Thank you :)
