### ISSUE TITLE
Hiding the top bar when on a video page.

### ISSUE THREAD

**Issue by dotdapple** [ParticleCore/Particle#178] opened 2015-12-31 05:28 UTC
When I play a video with “Fit to page in theater mode” enabled, the player doesn’t fit within my screen’s height with the top bar of the website.

I was hoping Fit to page… would be an alternative to Fullbrowser Mode, since the player would take up the space of the entire browser window *and* it would let me scroll down to the description and comments.

In short: I want an option to eliminate the top bar of YouTube while on a video page.

Thanks!

**Comment by ParticleCore** [comment] 2015-12-31 05:52
Duplicate of https://github.com/ParticleCore/Particle/issues/154

**Closed by ParticleCore** 2015-12-31 05:52 UTC
Labels: duplicate

**Comment by Eisys** [comment] 2015-12-31 15:37
If you are talking about the search bar and such, you could install [this syle](https://userstyles.org/styles/119282/youtube-no-masthead) with Stylish and set it to only activate on watch page like this: http://prntscr.com/9knwax
