### ISSUE TITLE
Distinguish between foreground & background tabs for auto-play setting

### ISSUE THREAD

**Issue by teradect** [ParticleCore/Particle#409] opened 2016-12-04 23:12 UTC
Could you add a function that distinguishes between foreground and background tabs for the stop-autoplay feature? I’d like to be able to control them separately so that I could let foreground videos autoplay but background videos not. Thanks!

**Comment by ParticleCore** [comment] 2016-12-04 23:17
Duplicate of #52

**Closed by ParticleCore** 2016-12-04 23:17 UTC
Labels: duplicate
