### ISSUE TITLE
YouTube Bugs

### ISSUE THREAD

**Issue by GKid94** [ParticleCore/Particle#358] opened 2016-10-11 01:05 UTC
Browser Name: Google Chrome

Browser Version: 53.0.2785.143 m (64-bit)

Operating System: Windows 10 Pro

Software Type: YoutubePlus Extension

Software Version: 1.5.7

Userscript Manager: Stylish

Userscript Version: 1.5.2

Problem Description: I've noticed some strange behavior on YouTube recently first the popup video started showing while i scroll in the search results(like in the screenshot) then the Repeat video option stopped working even when i turn it on and couple of other bugs, can you pls fix that :(
![2016-10-11 2](https://cloud.githubusercontent.com/assets/18757054/19255543/67333cca-8f5f-11e6-9e4a-df8437780a2d.png)

**Comment by ParticleCore** [comment] 2016-10-11 01:08
Your heavily customized YouTube is almost certainly causing a conflict with YT+. I still haven't been able to reproduce your problem so disable all extensions except YT+, restart and see if the problem still happens. If it does not happen then one, or more extensions are causing this conflict.

**Comment by ParticleCore** [comment] 2016-10-12 22:48
I will close this for now, if you still need help please follow the instructions in the previous reply.

**Closed by ParticleCore** 2016-10-12 22:48 UTC
Labels: invalid

**Comment by GKid94** [comment] 2016-10-12 22:58
I think Stylish was the problem and YT+ and him were confronting cuz i Removed Stylish and now YT works fine

**Comment by ParticleCore** [comment] 2016-10-12 23:02
Glad to hear it is working well again. Since it was Stylish, this means that one (or more) style just needs a tweak to not conflict with YT+ again, it shouldn't be too hard if you know how to modify it.

**Comment by GKid94** [comment] 2016-10-12 23:07
Nope i dont know anything about scrypts and codes
