### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by GKid94** [ParticleCore/Particle#338] opened 2016-09-17 21:43 UTC
Can you add an option so you could disable the black background in theater mode and an option to keep the video controls always showing that would be cool :D

**Comment by ParticleCore** [comment] 2016-09-17 22:46
Duplicate of https://github.com/ParticleCore/Particle/issues/148

**Closed by ParticleCore** 2016-09-17 22:46 UTC
Labels: duplicate

**Comment by GKid94** [comment] 2016-09-18 20:11
Im not a dev idk where to put those codes

**Comment by mauriciocolli** [comment] 2016-09-18 20:56
Install Stylish: https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe

Then just go to `Write new style`, then `Import` this:

```
@-moz-document regexp(".*youtube.com\\/watch.*") {
#theater-background {
    background: transparent !important;
}
}
```

Give a name and just save it

**Comment by GKid94** [comment] 2016-09-19 00:21
Its not working i still have black bars

**Comment by GKid94** [comment] 2016-09-19 00:23
Sry Its working i didnt do it correctly

**Comment by GKid94** [comment] 2016-09-19 00:45
Is there a code to keep the Video controls always showing?

**Comment by ParticleCore** [comment] 2016-09-19 00:54
@GKid94 Please don't abuse this issue tracker, if you want other functionalities provided by another user or located somewhere else please either contact him directly or use google. If what you want is to make a request then please post a new issue, but be advised of the readme note:

>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md
