### ISSUE TITLE
[suggest] Dark theme option

### ISSUE THREAD

**Issue by sqlandfriends** [ParticleCore/Particle#547] opened 2017-08-28 14:21 UTC
Hello I'm using Windows 10 Pro x64 with FF Nightly and want to get some better working addon for YT enhancement but what I need is included full yt Dark Theme feature is it possible that You will add it?

Regards, Horacy.

**Comment by ParticleCore** [comment] 2017-08-28 17:29
Duplicate of #193

**Closed by ParticleCore** 2017-08-28 17:29 UTC
Labels: duplicate
