### ISSUE TITLE
Pop-out video button in toolbar doesn't work

### ISSUE THREAD

**Issue by TomPiXX** [ParticleCore/Particle#447] opened 2017-01-25 08:52 UTC
Hi,

the pop-out button in the toolbar  doesn't work.
The small overlay buttons in the corner of the videos do.

![ytplus](https://cloud.githubusercontent.com/assets/9993839/22283699/08d3ee12-e2e4-11e6-90fe-3b2a722c3eea.jpg)

**Comment by Keith94** [comment] 2017-01-25 09:38
Works for me in Firefox 54

**Comment by TomPiXX** [comment] 2017-01-25 09:41
Strange. It does not work for a while now.
![ytplus2](https://cloud.githubusercontent.com/assets/9993839/22285144/c91d0054-e2ea-11e6-8c9b-e2e77c93964e.jpg)

**Comment by Keith94** [comment] 2017-01-25 10:52
Try in a [fresh profile](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles) or check the Browser Console for errors (Ctrl+Shift+J).

**Comment by ParticleCore** [comment] 2017-01-25 15:29
If you have your browser set to block all pop-ups or anything that could affect normal pop-up behavior then the pop-out feature will obviously not work.

Follow the troubleshooting guide like it was requested before opening the issue: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

**Comment by Fironet** [comment] 2017-01-26 06:18
Clicking this button opens the embed version of the video above all the other page elements, without any way to close it—even following subsequent page refreshes. Even hiding the element doesn't show the Particle settings button so I can't change any settings. Bit of an problematic bug.

**Comment by TomPiXX** [comment] 2017-01-26 06:51
So, the hint with the console was a good one.
Here's the result:

`GET 
https://www.youtube.com/ptracking [HTTP/2.0 499 No Reason Phrase 4ms]
Kopfzeilen
Parameter
Antwort
Aufrufliste
cpnbsHgWR3N5e0E5ltJei9puJWLaCFoP01gKkyLoghtml51plidAAVG-cAPCBAErWYspltypecontentugcptkyoutube_nonevideo_id4brdYZecLac

SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 1 column 1522 of the JSON data[Weitere Informationen] www.youtube.com:25:32
	getLocale https://www.youtube.com/:25:32
TypeError: api is undefined[Weitere Informationen]  www.youtube.com:1577:21
	popPlayer https://www.youtube.com/:1577:21
	handleToggles https://www.youtube.com/:1068:21`

**Comment by ParticleCore** [comment] 2017-01-26 13:30
@Fironet your issue is different than this one so please open a new issue, otherwise this will become a cross mess with different problems. Additionally, YT+ does not in any way use the embedded version anywhere, especially since it is disabled for embedded video pages. This is not a bug at all, you very likely have your browser set to always open new windows in the current tab or in a new tab, completely breaking the expected pop-out functionality. Remember to follow the troubleshooting guide: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

@TomPiXX I have already asked you to follow the troubleshooting guide for a second time, it appears that you still refuse to follow it despite the fact that I and another user expressed that this specific feature button is working properly. That guide lists all the steps that I would have asked here, if you do not follow them that is your choice, but do not expect me to repeat myself again or follow through with any support after you showed no desire to follow the guide.

That error in your console tells me that the player api is inaccessible and since I and another user do not have any problems, I can only assume that you have another extension running on YouTube that is causing this problem (Magic Actions, for example) or something else, which is why the troubleshooting guide is not a suggestion, it must be followed if these problems can have a chance at being solved.

**Comment by ParticleCore** [comment] 2017-01-26 13:46
And after paying more attention to your screenshot I can see that you have at least another YouTube extension installed called PotPlayer, which might be causing a conflict with YT+ since it is probably killing its access to the player api.

**Comment by ParticleCore** [comment] 2017-01-29 05:25
I will close this for now, if you still need help follow the instructions in the previous replies.

**Closed by ParticleCore** 2017-01-29 05:25 UTC
Labels: invalid
