### ISSUE TITLE
Disable HFR not quite working?

### ISSUE THREAD

**Issue by Eisys** [ParticleCore/Particle#435] opened 2017-01-13 23:35 UTC
Browser Name: Chrome
Browser Version: 56.0.2924.59 beta (64-bit)

Operating System: Win 10 Pro

Software Type: Userscript
Software Version: 1.7.6

Userscript Manager: Tampermonkey
Userscript Version:  4.2.7

Problem Description: I have 'Disable HFR (60fps)' enabled but it has started not working 100% of the time.

Steps to reproduce: Currently happening on this video: https://www.youtube.com/watch?v=pEkTL6cAtMM

Additional details: So yeah, a couple days ago I noticed it first. It happened on a then recently uploaded video. After I noticed, I refreshed and it was fixed. 
But with this video, after many refreshes and going through the troubleshoot guide, it still happens, for now atleast.
This is only the 2nd time so perhaps it's something wonky on my end but thought I'd let you know.

EDIT: 2 hours have passed and now that same video is working properly without 60fps. So I guess it only happens for some time after a video is uploaded.

**Comment by ParticleCore** [comment] 2017-01-14 04:29
I will close this for now, but if you find a way to make it easy to reproduce this in time do let me know so that I can try to find out what is different when a 60fps has been uploaded very recently that makes the feature not work properly.

**Comment by Eisys** [comment] 2017-02-15 01:27
https://www.youtube.com/watch?v=X2CNBuvvB4Y

Currently happening with this video. And it's 4 months old.
Tried resetting YT+ settings, then only enabling 'disable HFR' and it's still at 60fps.
Also tried on firefox, same thing.

Hope it does the same thing for you but if not, no big deal. Seems like a really rare occurence

**Comment by Keith94** [comment] 2017-02-15 02:01
^ Same happens for me too.

**Comment by ParticleCore** [comment] 2017-02-15 02:51
I can reproduce it too. It is quite strange, that video is displaying the streams' information in a way that only live streams usually do, this means that those streams are not immediately available for YT+ to change. Will try to find a way to get them to also work through the dash manifest.

**Comment by ParticleCore** [comment] 2017-02-15 04:57
I am sorry to say that disabling HFR on videos providing those streams through that method is no longer possible because YouTube is not including the equivalent non-HFR streams in that manifest.

I tried to trick the website into thinking the user was using a browser that was not capable of HFR streams, but it defaults to non-DASH streams, which have a max quality of 720p. I also went as far as to make it think it was running on a smartphone, but the result was the same.

It seems that if they go global with that delivery method (which is very odd since it uses a lot more data than the standard method) it will no longer be possible to disable HFR and the only option left is to disable DASH, which only offers up to 720p quality options.

**Comment by w00ter007** [comment] 2017-02-15 21:48
I'm having trouble viewing 60fps and have disable HFR option enabled.

Is it possible to make it auto-select the highest non-60fps quality (usually 480p)?

**Comment by ParticleCore** [comment] 2017-02-16 04:00
@w00ter007 YT+ currently does not have that flexibility. You can either set your default quality to 480p and change manually to higher when you want to, or the opposite. Alternatively, disabling DASH will guarantee no HFR streams, but will limit the quality options to 720p max.

**Comment by ParticleCore** [comment] 2017-04-01 14:10
A recent related issue lead me to re-check this situation again and noticed that YouTube has finally started including non-HFR streams in their new method. Will try to fix this as soon as I can.

**Closed** 2017-04-01 19:55 UTC
Labels: bug

**Comment by ParticleCore** [comment] 2017-04-01 19:59
Version 1.8.4 contains a fix for this problem, let me know if it works for you as well.
Sorry for not being able to tackle this sooner, but I just wasn't checking it as frequently as I once could.

**Comment by Eisys** [comment] 2017-04-01 21:05
Tested the new version with the 2nd video I linked and indeed it is fixed now, while with 1.8.3 it was still 60fps. 

Thanks!
