### ISSUE TITLE
When dash playback disabled, some videos won't load

### ISSUE THREAD

**Issue by ccrowles** [ParticleCore/Particle#149] opened 2015-11-23 11:41 UTC
Whenever I disable dash playback, some videos refuse to load and give me an error.
Example: https://www.youtube.com/watch?v=AblCIvAvPkQ
![screenshot02589](https://cloud.githubusercontent.com/assets/12866474/11335760/7954a67e-91df-11e5-9f6c-3aa0cfadf0fb.jpg)

**Comment by ParticleCore** [comment] 2015-11-23 12:25
I have just tested that video with DASH disabled and it plays correctly.

Please follow this troubleshooting guide to see if the problem is being caused by YT+ or not: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by ParticleCore** [comment] 2015-11-24 18:38
I will close this for now, if you still need help let me know.

**Closed by ParticleCore** 2015-11-24 18:38 UTC
Labels: invalid
