### ISSUE TITLE
"Sponsored" ads getting in below the video?

### ISSUE THREAD

**Issue by DiscoPanda84** [ParticleCore/Particle#635] opened 2017-12-14 19:31 UTC
Everything else seems to be working fine other than this one thing I just noticed has been sneaking by...

Cropped screenshot showing the "sponsored" content I'm seeing: https://i.imgur.com/6woiAps.png
URL of the page in the screenshot: https://www.youtube.com/watch?v=9B2117Juv1E

"Disable advertisements in the video page" IS checked.
"Disable advertisements outside the video page" IS checked.
"Enable advertisements only in videos from subscribed channels" IS NOT checked. (also, not even logged into YouTube anyways)

YouTube Plus version: 1.9.6
Browser version: Mozilla Firefox 52.5.2

**Comment by ParticleCore** [comment] 2017-12-14 19:51
Those are shopping ads that I was never able to catch, thus unable to stop them from showing. I am afraid that I will have to mark this one as won't fix for now since I simply cannot fix something that I don't get.

If you happen to get those again, could you open your browser console, type the following:

`$("#movie_player").getUpdatedConfigurationData();`

It should show a data object, right-click on it and select "Copy object".
After that open the notepad and paste your text and search for your IP address. Remove all of them and then share here the cleaned text without your IP address so that I can see the player data you were served and maybe I might find something that controls those ads, otherwise there is just nothing that I can do about it.

**Closed by ParticleCore** 2017-12-14 19:51 UTC
Labels: wontfix

**Comment by DiscoPanda84** [comment] 2017-12-15 01:03
Still have the tab for that page open. Using your command and doing what the image shows just gives me this:

`18:57:06.246 Object { url: "", args: Object, assets: Object, attrs: Object, params: Object, minVersion: "8.0.0", fallback: null, fallbackMessage: null, html5: true, disable: Object, 2 more… }`

However, I did get something useful with this command:

'copy($("#movie_player").getUpdatedConfigurationData());

(I just did a replace-all in Notepad to change my IP to 127.0.0.1 in the output from that, so it still gives an idea where my IP *would* be at normally.)

(I also copied the source of the div that had the ads, and the debug info provided by right-clicking the player and selecting "copy debug info", in case either of those would be of any help.)

[console object output.txt](https://github.com/ParticleCore/Particle/files/1561260/console.object.output.txt)
[source of ad div.txt](https://github.com/ParticleCore/Particle/files/1561261/source.of.ad.div.txt)
[copy debug info.txt](https://github.com/ParticleCore/Particle/files/1561262/copy.debug.info.txt)

**Comment by ParticleCore** [comment] 2017-12-15 01:35
Thanks for the data and I can see that something is not right. In the player configuration there is one flag that specifically controls the loading/displaying of ads, that is `ad3_module`. The current method (and one used since the previous extension) is to completely remove that field and it has been working well ever since.

What I can see in your details is that this field is not removed at all:

````json
    "relative_loudness": "-9.76899909973",
    "autoplay": "1",
    "ad3_module": "1", <---
    "status": "ok",
    "start": 1042.841
````

Which now makes more sense as to why it is showing those ads.

I just tested on my side with the same options enabled/disabled on ad loaded videos and the field is being removed correctly, which causes no ads to display. My only conclusion is that something on your end is causing this problem or causing a conflict with the extension, in which case I'd suggest following the troubleshooting guide: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

This is typically caused by conflicting extensions, if you happen to have similar YouTube extensions like Magic Actions, YouTube High Definition, etc. they might be causing this problem in the first place. Either way the troubleshooting guide should help clue in on the cause, but as far as I can see there is nothing broken on the extension that should be causing this.

**Comment by DiscoPanda84** [comment] 2017-12-15 01:49
Huh. Well, it doesn't seem to happen that much (loading the same page in another tab didn't bring up any ads there this time), and I don't have any other YouTube-specific extensions to try disabling, so I guess I'll just ignore it if I see it again. At least it's not those annoying preroll ads. (The preroll ads are the main reason I even bothered to start blocking ads on YouTube in the first place, actually. And from what I hear they're the main reason a lot of other people started to also. I'd say they kind of shot themselves in the foot on that one really...)

**Comment by ParticleCore** [comment] 2017-12-15 02:09
You should also take under consideration that the extension supports Firefox 48+  https://github.com/ParticleCore/Particle/blob/master/README.md

And you are using 52, that might be a factor as well, which is why it is asked that users follow the troubleshooting guide before opening an issue, there is no support provided for lower browser versions.
