### ISSUE TITLE
Feature: Show info about ratings and disabled comments in results

### ISSUE THREAD

**Issue by hank** [ParticleCore/Particle#244] opened 2016-03-28 00:41 UTC
I'd like at least my search results (and preferably all lists of videos) to show whether the video allows comments and ratings without me having to click it.  I've drawn a crude representation of this:

<img width="418" alt="screen shot 2016-03-27 at 8 31 00 pm" src="https://cloud.githubusercontent.com/assets/8534/14068790/230512d8-f45c-11e5-8e30-c44c811abb34.png">

I am a developer and would be happy to attempt to add this functionality if you give me some hints on where/how it should be added.  Thanks!

**Comment by ParticleCore** [comment] 2016-03-28 00:43
Duplicate of https://github.com/ParticleCore/Particle/issues/75

Also from the readme file:

>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md

**Closed by ParticleCore** 2016-03-28 00:43 UTC
Labels: duplicate
